import {freezeInvoice} from '../../../../lib/invoices';
import{jobStage}from'../../../../lib/funnel';
import {businessSettings} from '../../../../lib/business';
import {rawDb} from '../../../../db';import {ownerAuthorized,forbidden} from '../../owner-auth';import {clean,failure} from '../../records-utils';import {queueMessage,sendNotification,connections,siteUrl} from '../../../../lib/delivery';
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();return Response.json(connections(),{headers:{'Cache-Control':'no-store'}})}
export async function POST(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const b=await r.json() as any,db=rawDb(),j=await db.prepare('SELECT j.*,c.first_name,c.phone,c.email,c.language FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE j.id=?').bind(clean(b.jobId)).first<any>();if(!j)return Response.json({error:'Job not found.'},{status:404});
 if(b.action==='retry'){const n=await db.prepare('SELECT id FROM notifications WHERE id=? AND job_id=?').bind(clean(b.messageId),j.id).first<any>();if(!n)return Response.json({error:'Message not found.'},{status:404});return Response.json(await sendNotification(n.id))}
 if(!j.manage_token){j.manage_token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');await db.prepare('UPDATE jobs SET manage_token=? WHERE id=? AND manage_token IS NULL').bind(j.manage_token,j.id).run()}
 const contact=await businessSettings();let message=clean(b.message,2000);if(!['manual','sms','email'].includes(b.channel))return Response.json({error:'Choose how to send.'},{status:400});
 if(b.action==='eta'){if(['Cancelled','Completed','Paid'].includes(j.status))return Response.json({error:'This job is closed.'},{status:409});const eta=clean(b.eta,80);if(!eta)return Response.json({error:'Enter the arrival estimate you want to share.'},{status:400});await db.prepare('UPDATE jobs SET eta=?,eta_updated_at=? WHERE id=?').bind(eta,new Date().toISOString(),j.id).run();message=message||(j.language==='Spanish'?`Hola ${j.first_name}, soy ${contact.ownerName} de ${contact.name}. Voy en camino. Llegada estimada: ${eta}.`:`Hi ${j.first_name}, it's ${contact.ownerName} from ${contact.name}. I'm on my way. Estimated arrival: ${eta}.`);message+='\n'+(await siteUrl())+'/manage/'+j.manage_token;
 if(b.channel==='sms'&&!j.updates_opt_in)return Response.json({ok:true,status:'portal updated',message,phone:j.phone,notice:'Arrival updated on the appointment page. Customer has not enabled text updates.'});
 }else if(b.action==='document'){if(!['estimate','invoice'].includes(b.document))return Response.json({error:'Choose a document.'},{status:400});if((b.document==='invoice'?j.invoice_json:j.estimate_json)==='[]')return Response.json({error:'Save this document before sending it.'},{status:409});const invoice=b.document==='invoice'?await freezeInvoice(j):null;message=`Hi ${j.first_name}, your ${contact.name} ${b.document} is ready. View it here: ${await siteUrl()}${invoice?'/api':''}/manage/${j.manage_token}${invoice?'/document?type=invoice&revision='+invoice.revision:''}`;}
 else if(b.action!=='message'||!message)return Response.json({error:'Write a message first.'},{status:400});
 const result=await queueMessage(j,b.action==='document'?b.document:b.action,message,b.channel);if(b.action==='document'&&b.document==='estimate'&&['sent','delivered','accepted by provider'].includes(result.status))await jobStage(j.id,'sent').catch(()=>{});return Response.json({...result,message,phone:j.phone,email:j.email,portalUpdated:b.action==='eta'});
 }catch(e){return failure(e)}}
