// Offline recovery tooling. Not imported by the app and never given production credentials.
import {DatabaseSync} from 'node:sqlite';
import {createHash,randomBytes,scryptSync,createCipheriv,createDecipheriv} from 'node:crypto';
import {readFileSync,writeFileSync,mkdirSync,readdirSync,existsSync,lstatSync,realpathSync,copyFileSync,rmSync} from 'node:fs';
import {resolve,join,relative,dirname} from 'node:path';
export const tables=['customers','business_settings','cost_settings','vehicles','supplies','website_content','website_versions','website_media','website_public_media','owner_preferences','availability_rules','availability_blocks','jobs','notifications','media','expenses','mileage','trip_records','trip_jobs','trip_edits','supply_movements','estimate_funnels','ad_spend','invoice_records','invoice_versions','marketing_approvals','marketing_posts'];
export const hash=b=>createHash('sha256').update(b).digest('hex');
function write(p,b){mkdirSync(dirname(p),{recursive:true});writeFileSync(p,b,{mode:0o600})}
function inside(root,p){if(typeof p!=='string'||!p||p.includes('\\')||p.split('/').includes('..')||p.startsWith('/'))throw Error('Unsafe file path');const target=resolve(root,p);if(!target.startsWith(resolve(root)+'/'))throw Error('Unsafe file path');return target}
function snapshot(db){db.exec('BEGIN');try{const names=db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name NOT GLOB '__*' ").all().map(x=>x.name);const unexpected=names.filter(n=>!tables.includes(n)&&n!=='d1_migrations');if(unexpected.length)throw Error('Unregistered application tables: '+unexpected.join(','));const data=Object.fromEntries(tables.map(t=>[t,db.prepare(`SELECT * FROM "${t}" ORDER BY rowid`).all()]));db.exec('COMMIT');return data}catch(e){db.exec('ROLLBACK');throw e}}
export function redact(data){const tokens=new Set();function collect(v){if(Array.isArray(v)){v.forEach(collect);return}if(v&&typeof v==='object'){for(const [k,x]of Object.entries(v)){if(/(?:token|password|secret|api.?key)/i.test(k)&&typeof x==='string'&&x)tokens.add(x);collect(x)}}else if(typeof v==='string'&&/^[\[{]/.test(v)){try{collect(JSON.parse(v))}catch{}}}collect(data);
 function scrub(v,key=''){if(/(?:token|password|secret|api.?key)/i.test(key))return null;if(Array.isArray(v))return v.map(x=>scrub(x));if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,scrub(x,k)]));if(typeof v==='string'){if(/^[\[{]/.test(v)){try{return JSON.stringify(scrub(JSON.parse(v)))}catch{}}for(const token of tokens)v=v.split(token).join('[REDACTED]');return v.replace(/(\/manage\/)[a-f0-9]{64}/gi,'$1[REDACTED]').replace(/((?:access_token|refresh_token|api_key|secret|token)=)[^\s&"<>]+/gi,'$1[REDACTED]')}return v}return scrub(data)}
export function seal(bytes,password){if(typeof password!=='string'||password.length<20)throw Error('Use a unique recovery passphrase of at least 20 characters.');const salt=randomBytes(16),iv=randomBytes(12),key=scryptSync(password,salt,32),c=createCipheriv('aes-256-gcm',key,iv);c.setAAD(Buffer.from('Pressure Up recovery v1'));const ciphertext=Buffer.concat([c.update(bytes),c.final()]);return JSON.stringify({format:'pressure-up-encrypted-v1',kdf:'scrypt',salt:salt.toString('base64'),iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),ciphertext:ciphertext.toString('base64')})}
export function unseal(text,password){const x=JSON.parse(text);if(x.format!=='pressure-up-encrypted-v1'||x.kdf!=='scrypt')throw Error('Unsupported encrypted package');const key=scryptSync(password,Buffer.from(x.salt,'base64'),32),d=createDecipheriv('aes-256-gcm',key,Buffer.from(x.iv,'base64'));d.setAAD(Buffer.from('Pressure Up recovery v1'));d.setAuthTag(Buffer.from(x.tag,'base64'));return Buffer.concat([d.update(Buffer.from(x.ciphertext,'base64')),d.final()])}
function references(data){const refs=[];const add=(key,table,id,role,extra={})=>{if(key)refs.push({objectKey:key,table,recordId:id,role,...extra})};const job=id=>data.jobs.find(j=>j.id===id);
 for(const m of data.media){add(m.object_key,'media',m.id,'original',{jobId:m.job_id,customerId:job(m.job_id)?.customer_id,type:m.content_type,name:m.file_name});add(m.thumbnail_object_key,'media',m.id,'thumbnail',{jobId:m.job_id})}
 for(const e of data.expenses)add(e.receipt_object_key,'expenses',e.id,'receipt-original',{jobId:e.job_id,expectedSha:e.receipt_sha256||null});
 for(const m of data.website_media){add(m.object_key,'website_media',m.id,'website-original',{type:m.content_type,name:m.name});add(m.thumbnail_key,'website_media',m.id,'thumbnail')}
 for(const b of data.business_settings)add(b.owner_photo_key,'business_settings',b.id,'owner-photo');return refs}
function inventory(root){const index=JSON.parse(readFileSync(join(root,'object-index.json'),'utf8'));if(!Array.isArray(index)||index.some(k=>typeof k!=='string'||!k)||new Set(index).size!==index.length)throw Error('Invalid object index');return index.sort()}
export function validateRelationships(data){const by=Object.fromEntries(tables.map(t=>[t,new Set(data[t].map(r=>r.id??r.job_id??r.media_id))])),bad=[];const check=(table,column,parent,nullable=false)=>{for(const r of data[table]){const value=r[column];if(nullable&&(value==null||value===''))continue;if(!by[parent].has(value))bad.push(`${table}.${column}: ${r.id||r.job_id||r.media_id}`)}};
 for(const [t,c,p,n]of [['cost_settings','default_vehicle','vehicles',true],['jobs','customer_id','customers'],['media','job_id','jobs'],['expenses','job_id','jobs',true],['mileage','job_id','jobs',true],['trip_jobs','job_id','jobs'],['trip_jobs','trip_id','trip_records'],['trip_edits','trip_id','trip_records'],['trip_records','vehicle_id','vehicles',true],['invoice_records','job_id','jobs'],['invoice_versions','job_id','jobs'],['notifications','job_id','jobs',true],['notifications','customer_id','customers',true],['estimate_funnels','job_id','jobs',true],['jobs','funnel_id','estimate_funnels',true],['website_public_media','media_id','website_media'],['supply_movements','supply_id','supplies'],['supply_movements','expense_id','expenses',true],['supply_movements','job_id','jobs',true],['customers','merged_into','customers',true]])check(t,c,p,n);
 for(const a of data.marketing_approvals)if(!by[a.kind==='job'?'media':'website_media'].has(a.media_id))bad.push('marketing approval missing media: '+a.id);
 for(const post of data.marketing_posts)for(const key of JSON.parse(post.content_json).media||[]){const [kind,id]=key.split(':');if(!by[kind==='job'?'media':'website_media'].has(id))bad.push('marketing post missing media: '+post.id)}return bad}
export function createPackage({database,objects,migrations,output,password,offlineConfirmed=false,productionData=false}){if(!offlineConfirmed)throw Error('Offline/quiesced source confirmation is required. Do not use a changing live file store.');if(existsSync(output))throw Error('Output must be a new directory.');const db=new DatabaseSync(database,{readOnly:true});let data;try{data=snapshot(db)}finally{db.close()}const broken=validateRelationships(data);if(broken.length)throw Error('Broken relationships: '+broken.join('; '));const available=inventory(objects);const refs=references(data),keys=[...new Set(refs.map(r=>r.objectKey))],files=[];
 // Validate all references before creating a package. Missing objects never yield a successful backup.
 for(const key of keys){const p=inside(objects,hash(key));if(!available.includes(key)||!existsSync(p)||!lstatSync(p).isFile()||!realpathSync(p).startsWith(realpathSync(objects)+'/'))throw Error('Missing/unsafe referenced file: '+key);const bytes=readFileSync(p),sha256=hash(bytes),related=refs.filter(r=>r.objectKey===key);for(const ref of related)if(ref.expectedSha&&ref.expectedSha!==sha256)throw Error('Receipt checksum mismatch: '+key);files.push({objectKey:key,path:'files/'+hash(key),size:bytes.length,sha256,type:related.find(r=>r.type)?.type||(/\.pdf$/i.test(key)?'application/pdf':'application/octet-stream'),references:related})}
 mkdirSync(output,{recursive:true});try{for(const f of files){const bytes=readFileSync(inside(objects,hash(f.objectKey)));if(hash(bytes)!==f.sha256)throw Error('Source file changed during export');write(join(output,f.path),bytes)}
 const dbAgain=new DatabaseSync(database,{readOnly:true});let now;try{now=snapshot(dbAgain)}finally{dbAgain.close()}if(hash(JSON.stringify(now))!==hash(JSON.stringify(data)))throw Error('Database changed during export');
 const sqlFiles=readdirSync(migrations).filter(f=>f.endsWith('.sql')).sort(),schema=sqlFiles.map(name=>{const bytes=readFileSync(join(migrations,name));write(join(output,'schema',name),bytes);return {path:'schema/'+name,sha256:hash(bytes)}}),redacted=JSON.stringify(redact(data),null,2);write(join(output,'business-data.json'),redacted);const encrypted=seal(Buffer.from(JSON.stringify(data)),password);write(join(output,'recovery-records.encrypted.json'),encrypted);
 const orphans=inventory(objects).filter(key=>!keys.includes(key)),groups=Object.groupBy(files,f=>f.sha256),duplicates=Object.values(groups).filter(g=>g.length>1).map(g=>g.map(f=>f.objectKey));const manifest={format:'pressure-up-recovery-v1',createdAt:new Date().toISOString(),sourceMode:'offline-confirmed',productionData,counts:Object.fromEntries(tables.map(t=>[t,data[t].length])),files,schema,recordsSha256:hash(encrypted),businessSha256:hash(redacted),diagnostics:{missing:[],broken:[],orphans,duplicateByteGroups:duplicates},secretPolicy:'Business data redacted. Encrypted recovery records require a separately held passphrase. Original evidence files contain private business information; protect the whole directory/envelope.'};write(join(output,'manifest.json'),JSON.stringify(manifest,null,2));write(join(output,'manifest.authenticated.json'),seal(Buffer.from(JSON.stringify(manifest)),password));write(join(output,'COMPLETE'),hash(JSON.stringify(manifest)));return manifest}catch(e){rmSync(output,{recursive:true,force:true});throw e}}
export function restorePackage({input,target,password,migrateLinks=true}){if(existsSync(target))throw Error('Restore target already exists. Refusing overwrite.');const m=JSON.parse(readFileSync(join(input,'manifest.json'),'utf8'));if(m.format!=='pressure-up-recovery-v1'||readFileSync(join(input,'COMPLETE'),'utf8')!==hash(JSON.stringify(m)))throw Error('Incomplete or altered manifest');if(unseal(readFileSync(join(input,'manifest.authenticated.json'),'utf8'),password).toString()!==JSON.stringify(m))throw Error('Unauthenticated manifest');const encrypted=readFileSync(join(input,'recovery-records.encrypted.json'));if(hash(encrypted)!==m.recordsSha256)throw Error('Corrupt recovery records');if(hash(readFileSync(join(input,'business-data.json')))!==m.businessSha256)throw Error('Corrupt business export');const data=JSON.parse(unseal(encrypted.toString(),password));
 for(const t of tables)if(!Array.isArray(data[t])||data[t].length!==m.counts[t])throw Error('Table count mismatch: '+t);if(validateRelationships(data).length)throw Error('Broken restored relationships');for(const f of m.files){const b=readFileSync(inside(input,f.path));if(b.length!==f.size||hash(b)!==f.sha256)throw Error('Corrupt file: '+f.path);inside(join(target,'objects'),hash(f.objectKey))}for(const s of m.schema)if(hash(readFileSync(inside(input,s.path)))!==s.sha256)throw Error('Corrupt schema');
 // Default independent restore invalidates current customer links; historical evidence stays encrypted/protected.
 if(migrateLinks)for(const j of data.jobs)j.manage_token=randomBytes(32).toString('hex');for(const r of data.invoice_records)r.token=randomBytes(16).toString('hex');for(const p of data.marketing_posts)p.token=randomBytes(16).toString('hex');
 mkdirSync(target,{recursive:true});let db;try{db=new DatabaseSync(join(target,'business.sqlite'));db.exec('PRAGMA foreign_keys=ON');for(const s of m.schema)db.exec(readFileSync(inside(input,s.path),'utf8'));db.exec('BEGIN');db.exec('PRAGMA defer_foreign_keys=ON');for(const table of tables)for(const row of data[table]){const columns=Object.keys(row);if(columns.some(c=>!/^\w+$/.test(c)))throw Error('Unsafe column');db.prepare(`INSERT INTO "${table}" (${columns.map(c=>'"'+c+'"').join(',')}) VALUES (${columns.map(()=>'?').join(',')})`).run(...columns.map(c=>row[c]))}const fk=db.prepare('PRAGMA foreign_key_check').all();if(fk.length)throw Error('Restored foreign keys failed');db.exec('COMMIT');db.close();db=null;for(const f of m.files)write(inside(join(target,'objects'),hash(f.objectKey)),readFileSync(inside(input,f.path)));write(join(target,'objects','object-index.json'),JSON.stringify(m.files.map(f=>f.objectKey)));write(join(target,'restore-result.json'),JSON.stringify({counts:m.counts,fileCount:m.files.length,customerLinksRegenerated:migrateLinks,authReady:false,productionData:m.productionData},null,2));return {data,manifest:m}}catch(e){db?.close();rmSync(target,{recursive:true,force:true});throw e}}
