import {rawDb} from '../../../../db';
import {ownerAuthorized,forbidden} from '../../owner-auth';
import {editorState,checkMedia,publicBusiness} from '../../../../lib/website';
import {validateWebsite,mediaReferences} from '../../../../lib/website-model';
const headers={'Cache-Control':'private, no-store'};
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const db=rawDb(),id=new URL(r.url).searchParams.get('version');if(id){const version=await db.prepare('SELECT * FROM website_versions WHERE id=?').bind(id).first<any>();return version?Response.json({content:JSON.parse(version.content_json),description:version.description},{headers}):Response.json({error:'Version not found.'},{status:404})}const row=await editorState(),versions=await db.prepare('SELECT id,description,created_at FROM website_versions ORDER BY created_at DESC').all();return Response.json({draft:JSON.parse(row.draft_json),published:JSON.parse(row.published_json),revision:row.revision,versions:versions.results,currentContact:await publicBusiness()},{headers})}catch{return Response.json({error:'Could not load your website. Please try again.'},{status:500})}}
export async function POST(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const source=await r.text();if(source.length>150000)return Response.json({error:'This draft is too large.'},{status:413});const b=JSON.parse(source),db=rawDb(),row=await editorState();if(b.revision!==row.revision)return Response.json({error:'This draft changed on another device. Reload before saving.'},{status:409});const now=new Date().toISOString();
 if(b.action==='save'||b.action==='discard'||b.action==='restore'){
 let content;if(b.action==='save')content=validateWebsite(b.content);else if(b.action==='discard')content={...JSON.parse(row.published_json),contact:await publicBusiness()};else{const old=await db.prepare('SELECT content_json FROM website_versions WHERE id=?').bind(String(b.version)).first<any>();if(!old)return Response.json({error:'Version not found.'},{status:404});content=validateWebsite(JSON.parse(old.content_json))}await checkMedia(content);const result=await db.prepare("UPDATE website_content SET draft_json=?,base_contact_json=?,revision=revision+1,updated_at=? WHERE id='owner' AND revision=?").bind(JSON.stringify(content),b.action==='discard'?JSON.stringify(content.contact):row.base_contact_json,now,b.revision).run();if(!result.meta.changes)return Response.json({error:'Draft changed on another device. Reload first.'},{status:409});return Response.json({ok:true,revision:b.revision+1,draft:content},{headers});
 }
 if(b.action!=='publish')return Response.json({error:'Choose Save draft, Publish or Restore.'},{status:400});
 const content=validateWebsite(JSON.parse(row.draft_json));await checkMedia(content);const id=crypto.randomUUID(),json=JSON.stringify(content),previous=JSON.parse(row.published_json),contactChanged=JSON.stringify(previous.contact)!==JSON.stringify(content.contact),actual=await publicBusiness();
 if(contactChanged&&JSON.stringify(actual)!==row.base_contact_json&&JSON.stringify(actual)!==JSON.stringify(content.contact))return Response.json({error:'Business Settings changed since this draft began. Discard the draft to reload current contact details before changing them.'},{status:409});
 if(!contactChanged)content.contact=actual;const finalJSON=JSON.stringify(content),description=String(b.description||'Website update').trim().slice(0,200)||'Website update';const statements=[db.prepare("UPDATE website_content SET published_json=?,draft_json=?,base_contact_json=?,revision=revision+1,publish_id=?,updated_at=? WHERE id='owner' AND revision=?").bind(finalJSON,finalJSON,JSON.stringify(content.contact),id,now,b.revision),db.prepare("INSERT INTO website_versions (id,content_json,description,created_at) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM website_content WHERE publish_id=?)").bind(id,finalJSON,description,now,id)];
 if(contactChanged)statements.push(db.prepare("INSERT INTO business_settings (id,name,owner_name,phone,email,website) SELECT 'owner',?,?,?,?,? WHERE EXISTS (SELECT 1 FROM website_content WHERE publish_id=?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,owner_name=excluded.owner_name,phone=excluded.phone,email=excluded.email,website=excluded.website").bind(content.contact.name,content.contact.ownerName,content.contact.phone,content.contact.email,content.contact.website,id));
 statements.push(db.prepare('DELETE FROM website_public_media WHERE EXISTS (SELECT 1 FROM website_content WHERE publish_id=?)').bind(id));for(const photo of mediaReferences(content))statements.push(db.prepare('INSERT OR IGNORE INTO website_public_media (media_id) SELECT ? WHERE EXISTS (SELECT 1 FROM website_content WHERE publish_id=?)').bind(photo,id));
 const result=await db.batch(statements);if(!result[0].meta.changes)return Response.json({error:'Draft changed on another device. Reload first.'},{status:409});return Response.json({ok:true,revision:b.revision+1,version:id},{headers});
 }catch(e){return Response.json({error:e instanceof Error?e.message:'Could not save this draft.'},{status:400})}}
