import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import assert from 'node:assert/strict';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
const objects=new Map();
const DB={prepare(query){let values=[];return {bind(...v){values=v;return this},async first(column){const row=sql.prepare(query).get(...values);return column?row?.[column]??null:row??null},async all(){return {results:sql.prepare(query).all(...values)}},async raw(){return sql.prepare(query).all(...values).map(Object.values)},async run(){const r=sql.prepare(query).run(...values);return {success:true,meta:{changes:Number(r.changes)}}}}},async batch(queries){sql.exec('BEGIN');try{const results=[];for(const q of queries)results.push(await q.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__readinessEnv={DB,BUCKET:{async put(k,b,options){objects.set(k,{bytes:new Uint8Array(b),options})},async delete(k){objects.delete(k)},async get(k){const o=objects.get(k);return o?{body:o.bytes,httpMetadata:o.options?.httpMetadata}:null}}};
const output=mkdtempSync(join(tmpdir(),'pressure-up-readiness-'));
async function route(path){const file=join(output,path.replaceAll('/','_')+'.mjs');await build({entryPoints:[path],bundle:true,format:'esm',platform:'node',outfile:file,plugins:[{name:'isolated-bindings',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/^next\/headers$/},()=>({path:'headers',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?'export const env=globalThis.__readinessEnv;':`export async function headers(){return new Headers({'oai-authenticated-user-email':'lolitsedgy@gmail.com'})}`}))}}]});return import(file)}
const owner={'oai-authenticated-user-email':'lolitsedgy@gmail.com'},api=await route('app/api/bookings/route.ts'),jobs=await route('app/api/owner/bookings/route.ts'),media=await route('app/api/owner/media/[id]/route.ts');
const tomorrow=new Date();tomorrow.setUTCDate(tomorrow.getUTCDate()+10);const date=tomorrow.toISOString().slice(0,10);
const {testPng}=await import('./test-photo.mjs');const original=testPng(),form=new FormData();form.set('data',JSON.stringify({customer:{firstName:'Quality',lastName:'Test',phone:'+12025550123',email:'quality@example.test',address:'100 Test Street, Lawndale, CA'},job:{date,window:'8–9 AM',price:120,payment:'Cash after service'},selection:{services:['driveway'],city:'Lawndale'}}));form.append('photos',new Blob([original],{type:'image/png'}),'high-resolution-original.png');form.set('thumbnail0',new Blob([original.subarray(0,100)],{type:'image/jpeg'}),'thumbnail.jpg');
const response=await api.POST(new Request('https://pressureup.test/api/bookings',{method:'POST',body:form}));const saved=await response.json();assert.equal(response.status,201,JSON.stringify(saved));
const m=sql.prepare('SELECT * FROM media WHERE job_id=?').get(saved.jobId);assert.ok(m.thumbnail_object_key);assert.deepEqual(Buffer.from(objects.get(m.object_key).bytes),original);assert.notDeepEqual(objects.get(m.object_key).bytes,objects.get(m.thumbnail_object_key).bytes);
const full=await media.GET(new Request('https://pressureup.test/api/owner/media/'+m.id),{params:Promise.resolve({id:m.id})});assert.equal(full.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await full.arrayBuffer()),original);assert.match(full.headers.get('content-disposition'),/high-resolution-original.png/);
assert.equal((await jobs.GET(new Request('https://pressureup.test/api/owner/bookings'))).status,403);
console.log('PASS: customer multipart upload stores and serves the exact original bytes, linked to its job; thumbnail is separate; owner API rejects anonymous access.');
const patch=async body=>{const response=await jobs.PATCH(new Request('https://pressureup.test/api/owner/bookings',{method:'PATCH',headers:{...owner,'Content-Type':'application/json'},body:JSON.stringify({id:saved.jobId,...body})}));return {status:response.status,data:await response.json()}};
assert.equal((await patch({action:'status',status:'Confirmed'})).status,200);
let rows=await (await jobs.GET(new Request('https://pressureup.test/api/owner/bookings',{headers:owner}))).json();assert.equal(rows.filter(r=>r.job.id===saved.jobId&&r.job.scheduledDate===date&&r.job.status==='Confirmed').length,1);
const changed=new Date(date+'T12:00:00Z');changed.setUTCDate(changed.getUTCDate()+1);const changedDate=changed.toISOString().slice(0,10);
assert.equal((await patch({action:'reschedule',date:changedDate,window:'afternoon'})).status,200);
rows=await (await jobs.GET(new Request('https://pressureup.test/api/owner/bookings',{headers:owner}))).json();assert.equal(rows.length,1);assert.equal(rows[0].job.scheduledDate,changedDate);assert.equal(rows[0].job.arrivalWindow,'12–1 PM');assert.equal(sql.prepare('SELECT trip_date FROM trip_records').get().trip_date,changedDate);
assert.equal((await patch({action:'status',status:'Completed'})).status,200);assert.equal(sql.prepare('SELECT status FROM jobs').get().status,'Completed');assert.notEqual(sql.prepare('SELECT invoice_json FROM jobs').get().invoice_json,'[]');assert.equal((await patch({action:'reschedule',date,window:'morning'})).status,409);
// Cancellation changes the same source record and releases public availability.
sql.prepare("UPDATE jobs SET status='Confirmed' WHERE id=?").run(saved.jobId);assert.equal((await patch({action:'cancel',mode:'manual'})).status,200);assert.equal(sql.prepare('SELECT count(*) AS n FROM jobs').get().n,1);assert.equal(sql.prepare('SELECT status FROM jobs').get().status,'Cancelled');sql.prepare("UPDATE jobs SET status='Completed' WHERE id=?").run(saved.jobId);
console.log('PASS: confirm, reschedule, completion and cancellation update one job record; the calendar data contains the correct date/window/status; completion prepares the invoice; mileage stays linked.');
const documents=await route('app/api/owner/documents/route.ts');
const {PDFDocument}=await import('pdf-lib');
assert.equal((await documents.GET(new Request(`https://pressureup.test/api/owner/documents?id=${saved.jobId}&type=receipt`,{headers:owner}))).status,409);
assert.equal((await patch({action:'record_payment',amount:120,date,method:'Cash'})).status,200);assert.equal((await patch({action:'record_payment',amount:120,date,method:'Cash'})).status,409);
for(const type of ['estimate','invoice','receipt','work-order','completion']){const r=await documents.GET(new Request(`https://pressureup.test/api/owner/documents?id=${saved.jobId}&type=${type}&download=1`,{headers:owner}));assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');assert.match(r.headers.get('content-disposition'),/^attachment; filename=".*\.pdf"$/);const bytes=Buffer.from(await r.arrayBuffer());assert.equal(bytes.subarray(0,5).toString(),'%PDF-');assert.ok((await PDFDocument.load(bytes)).getPageCount()>0);writeFileSync(`/workspace/scratch/pressure-up-test-${type}.pdf`,bytes)}
for(const [path,url] of [['summary',`?from=${date.slice(0,4)}-01-01&to=${date.slice(0,4)}-12-31`],['job-file',`?id=${saved.jobId}`]]){const report=await route(`app/api/owner/${path}/route.ts`),r=await report.GET(new Request(`https://pressureup.test/api/owner/${path}${url}`,{headers:owner}));assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'application/pdf');const bytes=Buffer.from(await r.arrayBuffer());assert.ok((await PDFDocument.load(bytes)).getPageCount()>0);writeFileSync(`/workspace/scratch/pressure-up-test-${path}.pdf`,bytes)}
const portal=await route('app/api/manage/[token]/document/route.ts'),token=sql.prepare('SELECT manage_token FROM jobs WHERE id=?').get(saved.jobId).manage_token;assert.equal((await portal.GET(new Request('https://pressureup.test/document?type=invoice'),{params:Promise.resolve({token})})).status,200);assert.equal((await portal.GET(new Request('https://pressureup.test/document?type=invoice'),{params:Promise.resolve({token:'0'.repeat(64)})})).status,404);
console.log('PASS: all five job document types, summary and job file produce parseable genuine PDFs with correct headers; customer document links are scoped by unguessable token; duplicate cash recording rejected.');
const settings=await route('app/api/owner/settings/route.ts'),contact=await route('app/api/contact/route.ts');const updated={name:'Pressure Up',ownerName:'Edgar Torres',phone:'+12025550199',email:'business@example.test',website:'https://pressureup.test',baseAddress:'100 Private Test Base'};
assert.equal((await settings.PUT(new Request('https://pressureup.test/settings',{method:'PUT',headers:{...owner,'Content-Type':'application/json'},body:JSON.stringify(updated)}))).status,200);const publicContact=await (await contact.GET()).json();assert.equal(publicContact.phone,updated.phone);assert.equal(publicContact.email,updated.email);assert.equal(publicContact.baseAddress,undefined);assert.equal((await settings.GET(new Request('https://pressureup.test/settings'))).status,403);
const reports=await route('app/api/owner/reports/route.ts');let csv=await (await reports.GET(new Request(`https://pressureup.test/reports?type=tax&from=${date.slice(0,4)}-01-01&to=${date.slice(0,4)}-12-31`,{headers:owner}))).text();assert.match(csv,/"Recorded payments","120"/);assert.ok(csv.includes(saved.jobId));assert.match(csv,/Cash/);assert.match(csv,/business@example.test/);csv=await (await reports.GET(new Request('https://pressureup.test/reports?type=tax&from=2000-01-01&to=2000-12-31',{headers:owner}))).text();assert.match(csv,/"Recorded payments","0"/);
const communicate=await route('app/api/owner/communicate/route.ts');sql.prepare("UPDATE jobs SET status='Confirmed',paid_at=NULL,paid_amount=NULL WHERE id=?").run(saved.jobId);const eta=await communicate.POST(new Request('https://pressureup.test/communicate',{method:'POST',headers:{...owner,'Content-Type':'application/json'},body:JSON.stringify({action:'eta',jobId:saved.jobId,eta:'12:45 PM',channel:'manual'})}));const etaResult=await eta.json();assert.equal(eta.status,200);assert.equal(etaResult.status,'draft');assert.match(etaResult.message,/Quality/);assert.match(etaResult.message,/Pressure Up/);assert.match(etaResult.message,/12:45 PM/);assert.match(etaResult.message,/https:\/\/pressureup.test\/manage\//);assert.equal(etaResult.phone,'+12025550123');assert.equal(sql.prepare('SELECT eta FROM jobs').get().eta,'12:45 PM');
const upload=await route('app/api/owner/uploads/route.ts'),after=new FormData();after.set('jobId',saved.jobId);after.set('file',new Blob([original],{type:'image/png'}),'after-photo.png');assert.equal((await upload.POST(new Request('https://pressureup.test/uploads',{method:'POST',headers:owner,body:after}))).status,201);const afterRecord=sql.prepare("SELECT * FROM media WHERE file_name='after-photo.png'").get();assert.equal(afterRecord.job_id,saved.jobId);assert.deepEqual(Buffer.from(objects.get(afterRecord.object_key).bytes),original);
const dates=await route('lib/availability.ts');assert.equal(dates.dateKey('TUE, September 15','2026-09-06'),'2026-09-15');sql.prepare("UPDATE jobs SET scheduled_date='TUE, September 15',created_at='2026-09-06 18:44:15' WHERE id=?").run(saved.jobId);sql.exec(readFileSync('drizzle/0007_normalize_job_dates.sql','utf8'));assert.equal(sql.prepare('SELECT scheduled_date FROM jobs').get().scheduled_date,'2026-09-15');
console.log('PASS: owner uploads retain original bytes; business contact settings stay private where appropriate and feed exports; revenue filters reflect cash payments; manual ETA produces a draft; the exact legacy calendar-date migration is verified.');
export {sql,objects,route,owner,saved,date,jobs,output};
