import {invoiceInfo,initializeInvoice,changeInvoice,freezeInvoice,invoiceSnapshot} from '../../../../lib/invoices';
import{jobStage}from'../../../../lib/funnel';
import {env} from '@/lib/runtime-env';import {rawDb} from '../../../../db';import {forbidden,ownerAuthorized} from '../../owner-auth';import {clean,moneyValue,isoDate,failure} from '../../records-utils';
import {dateKey,isBlocked,LA_TODAY} from '../../../../lib/availability';import {availabilityRows} from '../../../../lib/availability-data';
import {draftTrip} from '../../../../lib/job-costs';
function jobShape(j:any){return {id:j.id,leadSource:j.lead_source,campaign:j.campaign,customerId:j.customer_id,service:j.service,scheduledDate:dateKey(j.scheduled_date,j.created_at),arrivalWindow:j.arrival_window,price:j.price,status:j.status,paymentMethod:j.payment_method,estimateJson:j.estimate_json,invoiceJson:j.invoice_json,invoiceState:j.invoice_state,manageToken:j.manage_token,cancelledAt:j.cancelled_at,cancellationReason:j.cancellation_reason,cancelledBy:j.cancelled_by,notificationStatus:j.notification_status,paidAt:j.paid_at,paidAmount:j.paid_amount,customerNote:j.customer_note,eta:j.eta,etaUpdatedAt:j.eta_updated_at,updatesOptIn:!!j.updates_opt_in,durationMinutes:j.duration_minutes}}
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const p=new URL(r.url).searchParams,id=p.get('id'),db=rawDb();if(id){const [files,notes]=await Promise.all([db.prepare('SELECT id,content_type,file_name,thumbnail_object_key FROM media WHERE job_id=? ORDER BY created_at').bind(id).all(),db.prepare('SELECT id,message,status,channel,created_at,provider_id,sent_at FROM notifications WHERE job_id=? ORDER BY created_at DESC').bind(id).all()]);const job=await db.prepare('SELECT * FROM jobs WHERE id=?').bind(id).first();return Response.json({files:files.results,notes:notes.results,invoice:job?await invoiceInfo(job):null},{headers:{'Cache-Control':'no-store'}})}const rows=await db.prepare('SELECT j.*,(SELECT state FROM invoice_records WHERE job_id=j.id) AS invoice_state,c.first_name,c.last_name,CASE WHEN length(j.service_address)>0 THEN j.service_address ELSE c.address END AS address,c.phone,c.email FROM jobs j JOIN customers c ON c.id=j.customer_id ORDER BY j.created_at DESC').all<any>();return Response.json(rows.results.map(j=>({job:jobShape(j),customer:{firstName:j.first_name,lastName:j.last_name,address:j.address,phone:j.phone,email:j.email}})),{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function PATCH(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const b=await r.json() as any,db=rawDb(),j=await db.prepare('SELECT j.*,c.first_name FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE j.id=?').bind(clean(b.id)).first<any>();if(!j)return Response.json({error:'Job not found.'},{status:404});
 if(b.action==='reschedule'){if(j.paid_at||['Cancelled','Completed','Paid','Invoice sent'].includes(j.status))return Response.json({error:'Only open appointments can be rescheduled.'},{status:409});const date=dateKey(String(b.date||'')),window=b.window;if(!isoDate(date)||date<LA_TODAY()||!['morning','afternoon'].includes(window))return Response.json({error:'Choose a current or future date and arrival window.'},{status:400});const availability=await availabilityRows();if(isBlocked(date,window,availability.rules,availability.blocks,availability.jobs.filter((x:any)=>x.id!==j.id),j.duration_minutes))return Response.json({error:'That arrival window is unavailable. Choose another.'},{status:409});const start=window==='morning'?480:720,result=await db.prepare("UPDATE jobs SET scheduled_date=?,arrival_window=? WHERE id=? AND NOT EXISTS (SELECT 1 FROM jobs other WHERE other.id!=? AND other.scheduled_date=? AND other.status!='Cancelled' AND (CASE WHEN other.arrival_window LIKE '12%' THEN 720 ELSE 480 END)<? AND (CASE WHEN other.arrival_window LIKE '12%' THEN 720 ELSE 480 END)+60+other.duration_minutes+30>?)").bind(date,window==='morning'?'8–9 AM':'12–1 PM',j.id,j.id,date,start+60+j.duration_minutes+30,start).run();if(!result.meta.changes)return Response.json({error:'That window was just taken. Choose another.'},{status:409});await db.prepare("UPDATE trip_records SET trip_date=? WHERE status='draft' AND id IN (SELECT trip_id FROM trip_jobs WHERE job_id=?) AND (SELECT count(*) FROM trip_jobs l WHERE l.trip_id=trip_records.id)=1").bind(date,j.id).run();return Response.json({ok:true})}
 if(['delete_invoice','revise_invoice','void_invoice'].includes(b.action)){
 if(j.paid_at||j.status==='Paid')return Response.json({error:'Paid invoices must be retained unchanged.'},{status:409});
 const m=await initializeInvoice(j);if(b.token!==m.token)return Response.json({error:'Reload the invoice before changing it.'},{status:409});
 if(b.action==='delete_invoice'){const history=await db.prepare('SELECT id FROM invoice_versions WHERE job_id=? LIMIT 1').bind(j.id).first();if(m.state!=='Draft'||history||b.confirm!=='DELETE DRAFT')return Response.json({error:'Only a never-shared, unpaid draft can be deleted. Confirm DELETE DRAFT.'},{status:409});
 const estimate=JSON.parse(j.estimate_json).reduce((n:number,x:any)=>n+Number(x.amount),0);await changeInvoice(j,m,{state:'None',items:'[]',price:estimate});return Response.json({ok:true})}
 if(b.action==='void_invoice'){if(m.state!=='Sent'||b.confirm!=='VOID INVOICE')return Response.json({error:'Confirm VOID INVOICE for an unpaid sent invoice.'},{status:409});await changeInvoice(j,m,{state:'Void'});return Response.json({ok:true})}
 if(m.state!=='Sent')return Response.json({error:'Only a sent invoice needs a correction revision.'},{status:409});await freezeInvoice(j);const current=await initializeInvoice(j);await changeInvoice(j,current,{state:'Draft',revision:current.revision+1});return Response.json({ok:true})}
 if(b.action==='document'){if(j.paid_at||j.status==='Paid')return Response.json({error:'This job has a recorded payment. Keep its invoice unchanged.'},{status:409});if(!['estimate','invoice'].includes(b.document)||!Array.isArray(b.items)||!b.items.length||b.items.length>50)return Response.json({error:'Add between 1 and 50 line items.'},{status:400});const items=b.items.map((x:any)=>({name:clean(x.name),amount:Math.round(Number(x.amount)*100)/100}));if(items.some((x:any)=>!x.name||!Number.isFinite(x.amount)||Math.abs(x.amount)>1000000))return Response.json({error:'Enter valid descriptions and prices.'},{status:400});const total=moneyValue(items.reduce((n:number,x:any)=>n+x.amount,0));
 if(b.document==='invoice'){const m=await initializeInvoice(j);if(!['None','Draft'].includes(m.state))return Response.json({error:'Create a correction revision before editing a sent invoice.'},{status:409});if(b.token!==undefined&&b.token!==m.token)return Response.json({error:'Invoice changed. Reload before saving.'},{status:409});await changeInvoice(j,m,{items:JSON.stringify(items),price:total,state:'Draft'})}
 else {const updated=await db.prepare("UPDATE jobs SET estimate_json=?,price=CASE WHEN invoice_json='[]' THEN ? ELSE price END WHERE id=? AND paid_at IS NULL AND status!='Paid'").bind(JSON.stringify(items),total,j.id).run();if(!updated.meta.changes)return Response.json({error:'Payment was recorded. Reload this job.'},{status:409})}return Response.json({ok:true})}
 if(b.action==='copy_to_invoice'){if(j.paid_at||j.status==='Paid'||j.invoice_json!=='[]')return Response.json({error:'An invoice already exists or payment was recorded.'},{status:409});const m=await initializeInvoice(j);if(!['None','Draft'].includes(m.state))return Response.json({error:'This invoice is protected.'},{status:409});await changeInvoice(j,m,{items:j.estimate_json,state:'Draft'});return Response.json({ok:true})}
 if(b.action==='status'){if(j.paid_at||j.status==='Cancelled')return Response.json({error:'This job is closed.'},{status:409});if(!['Requested','Confirmed','In progress','Completed','Invoice sent'].includes(b.status))return Response.json({error:'Choose a valid job status.'},{status:400});if(b.status==='Invoice sent')await freezeInvoice(j);const changed=await db.prepare("UPDATE jobs SET status=?,invoice_json=CASE WHEN ?='Completed' AND invoice_json='[]' THEN estimate_json ELSE invoice_json END WHERE id=? AND paid_at IS NULL AND status!='Paid'").bind(b.status,b.status,j.id).run();if(!changed.meta.changes)return Response.json({error:'Payment was recorded. Reload this job.'},{status:409});if(['Confirmed','In progress','Completed','Invoice sent'].includes(b.status))await jobStage(j.id,'booked').catch(()=>{});if(b.status==='Completed'){await draftTrip(j.id,true);await jobStage(j.id,'completed').catch(()=>{})}return Response.json({ok:true})}
 if(b.action==='record_payment'){if(j.paid_at)return Response.json({error:'Payment is already recorded for this job.'},{status:409});if(j.status==='Cancelled'||!isoDate(b.date)||!['Cash','Card (received externally)','Bank transfer','Check'].includes(b.method))return Response.json({error:'Choose a payment date and method for an active job.'},{status:400});const inv=await initializeInvoice(j);if(inv.state==='Void'||(inv.state==='None'&&j.invoice_json==='[]'))return Response.json({error:'Save an invoice before recording its payment.'},{status:409});const amount=moneyValue(b.amount);if(amount!==moneyValue(j.price))return Response.json({error:'The received amount must match the invoice total. Edit the invoice first if the final price changed.'},{status:400});const recorded=await db.prepare("UPDATE jobs SET status='Paid',paid_at=?,paid_amount=?,payment_method=?,invoice_json=CASE WHEN invoice_json='[]' THEN estimate_json ELSE invoice_json END WHERE id=? AND paid_at IS NULL AND price=? AND invoice_json=? AND EXISTS (SELECT 1 FROM invoice_records WHERE job_id=? AND token=?)").bind(b.date,amount,b.method,j.id,j.price,j.invoice_json,j.id,inv.token).run();if(!recorded.meta.changes)return Response.json({error:'Payment is already recorded for this job.'},{status:409});await draftTrip(j.id,true);await jobStage(j.id,'paid').catch(()=>{});return Response.json({ok:true})}
 if(b.action==='manual_sent'){const note=await db.prepare("SELECT type FROM notifications WHERE id=? AND job_id=? AND channel='manual'").bind(clean(b.noteId),j.id).first<any>();if(note?.type==='invoice')await freezeInvoice(j);if(note?.type==='estimate')await jobStage(j.id,'sent').catch(()=>{});await db.prepare("UPDATE notifications SET status='sent manually' WHERE id=? AND job_id=? AND channel='manual'").bind(clean(b.noteId),j.id).run();return Response.json({ok:true})}
 if(b.action!=='cancel')return Response.json({error:'Choose an action.'},{status:400});if(['Completed','Paid'].includes(j.status)||j.paid_at)return Response.json({error:'Completed or paid work cannot be cancelled here. Contact the customer to arrange any correction or refund.'},{status:409});if(j.status==='Cancelled')return Response.json({ok:true});const message=clean(b.message,2000)||`Hi ${j.first_name}, your Pressure Up appointment on ${j.scheduled_date} is cancelled. You can request a new date on our website. — Edgar`;
 await db.batch([db.prepare("UPDATE jobs SET status='Cancelled',cancelled_at=?,cancellation_reason=?,cancelled_by='owner',notification_status=? WHERE id=?").bind(new Date().toISOString(),clean(b.reason)||'Owner cancelled',b.mode==='automatic'?'queued — not sent':'manual draft',j.id),db.prepare('INSERT INTO notifications (id,job_id,customer_id,type,channel,status,message) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),j.id,j.customer_id,'owner_cancelled',b.mode==='automatic'?'sms':'manual',b.mode==='automatic'?'queued':'draft',message)]);return Response.json({ok:true});
 }catch(e){return failure(e)}}
export async function DELETE(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const id=new URL(r.url).searchParams.get('id')||'',db=rawDb(),j=await db.prepare('SELECT paid_at,status FROM jobs WHERE id=?').bind(id).first<any>();if(!j)return Response.json({error:'Job not found.'},{status:404});const expense=await db.prepare('SELECT id FROM expenses WHERE job_id=? LIMIT 1').bind(id).first(),trip=await db.prepare('SELECT id FROM mileage WHERE job_id=? LIMIT 1').bind(id).first();const linked=await db.prepare("SELECT l.job_id FROM trip_jobs l JOIN trip_records t ON t.id=l.trip_id WHERE l.job_id=? AND (t.status!='draft' OR t.actual_miles IS NOT NULL OR EXISTS (SELECT 1 FROM trip_edits e WHERE e.trip_id=t.id)) UNION SELECT job_id FROM supply_movements WHERE job_id=? LIMIT 1").bind(id,id).first();if(j.paid_at||j.status==='Paid'||expense||trip||linked)return Response.json({error:'This job has financial records attached. Keep it for your records.'},{status:409});const protectedInvoice=await db.prepare("SELECT job_id FROM invoice_versions WHERE job_id=? UNION SELECT job_id FROM invoice_records WHERE job_id=? AND state IN ('Sent','Void','Paid') LIMIT 1").bind(id,id).first();if(protectedInvoice)return Response.json({error:'This job has an issued invoice. Preserve its history.'},{status:409});const files=await db.prepare('SELECT object_key,thumbnail_object_key FROM media WHERE job_id=?').bind(id).all<any>();await db.batch([db.prepare('DELETE FROM trip_jobs WHERE job_id=?').bind(id),db.prepare("DELETE FROM trip_records WHERE status='draft' AND id NOT IN (SELECT trip_id FROM trip_jobs) AND id NOT IN (SELECT trip_id FROM trip_edits)"),db.prepare('DELETE FROM media WHERE job_id=?').bind(id),db.prepare('DELETE FROM notifications WHERE job_id=?').bind(id),db.prepare('DELETE FROM estimate_funnels WHERE job_id=?').bind(id),db.prepare('DELETE FROM invoice_records WHERE job_id=?').bind(id),db.prepare('DELETE FROM jobs WHERE id=?').bind(id)]);for(const f of files.results){await env.BUCKET.delete(f.object_key);if(f.thumbnail_object_key)await env.BUCKET.delete(f.thumbnail_object_key)};return Response.json({ok:true})}catch(e){return failure(e)}}
