'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {thumbnail} from '../bookings/JobMedia';
import {sectionNames,serviceRange,type Website,type Words} from '../../../lib/website-model';
const field='mt-2 w-full min-w-0 rounded-xl border border-[#d7ded8] bg-white p-3 text-base';
const btn='min-h-11 rounded-full border border-[#d7ded8] bg-white px-4 py-2 text-sm font-semibold disabled:opacity-40';
const primary=btn+' !bg-[#173b32] text-white';
async function req(path:string,init?:RequestInit){const r=await fetch(path,init),d=await r.json();if(!r.ok)throw Error(d.error||'Please try again.');return d}
export default function Editor(){
 const [draft,setDraft]=useState<Website|null>(null),[saved,setSaved]=useState(''),[published,setPublished]=useState(''),[revision,setRevision]=useState(0),[versions,setVersions]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[panel,setPanel]=useState('website'),[section,setSection]=useState<keyof typeof sectionNames>('hero'),[serviceId,setServiceId]=useState('driveway'),[language,setLanguage]=useState<'en'|'es'>('en'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[confirmAction,setConfirmAction]=useState(''),[description,setDescription]=useState(''),[viewVersion,setViewVersion]=useState<any>(null),[previewMode,setPreviewMode]=useState('mobile'),[showPreview,setShowPreview]=useState(false),[previewWidth,setPreviewWidth]=useState(390),[picker,setPicker]=useState<((id:string)=>void)|null>(null),[mediaCategory,setMediaCategory]=useState('website'),[includeArchived,setIncludeArchived]=useState(false),[unlock,setUnlock]=useState(false);
 const frame=useRef<HTMLIFrameElement>(null),previewHost=useRef<HTMLDivElement>(null),drag=useRef<number|null>(null),uploadInput=useRef<HTMLInputElement>(null);
 const dirty=!!draft&&JSON.stringify(draft)!==saved,pending=!!draft&&JSON.stringify(draft)!==published;
 async function load(){const d=await req('/api/owner/website');setDraft(d.draft);setSaved(JSON.stringify(d.draft));setPublished(JSON.stringify(d.published));setRevision(d.revision);setVersions(d.versions)}
 async function loadMedia(){setMedia(await req('/api/owner/website/media'))}
 useEffect(()=>{if(new URLSearchParams(location.search).get('section')==='about')setSection('about');Promise.all([load(),loadMedia()]).catch(e=>setNotice(e.message))},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
 const previewContent=viewVersion?.content||draft;
 function sendPreview(){if(previewContent)frame.current?.contentWindow?.postMessage({type:'pressure-up-draft',content:previewContent,language},location.origin)}
 useEffect(()=>{sendPreview()},[previewContent,language,showPreview,previewMode]);
 useEffect(()=>{const handle=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='pressure-up-preview-ready')sendPreview();if(e.data?.type==='pressure-up-select'&&!viewVersion){const id=e.data.section;if(Object.hasOwn(sectionNames,id)){setSection(id);setPanel('website');if(e.data.service){setServiceId(e.data.service);setPanel('services')}}else if(['promotion','contact'].includes(id))setPanel(id==='promotion'?'promotions':'contact');setShowPreview(false)}};window.addEventListener('message',handle);return()=>window.removeEventListener('message',handle)},[previewContent,language,viewVersion]);
 useEffect(()=>{if(!previewHost.current)return;const ob=new ResizeObserver(entries=>setPreviewWidth(entries[0].contentRect.width));ob.observe(previewHost.current);return()=>ob.disconnect()},[!!draft,showPreview]);
 function change(fn:(d:Website)=>void){setDraft(old=>{if(!old)return old;const next=structuredClone(old);fn(next);return next});setViewVersion(null)}
 function move(i:number,n:number){change(d=>{const next=i+n;if(next<0||next>=d.sections.length)return;[d.sections[i],d.sections[next]]=[d.sections[next],d.sections[i]]})}
 async function saveDraft(){if(!draft)return revision;const d=await req('/api/owner/website',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',revision,content:draft})});setDraft(d.draft);setSaved(JSON.stringify(d.draft));setRevision(d.revision);return d.revision}
 async function action(kind:string){setBusy(true);setNotice('');try{let rev=revision;if(kind==='save'){await saveDraft();setNotice('Draft saved. Visitors still see your published website.')}else{if(kind==='publish'&&dirty)rev=await saveDraft();await req('/api/owner/website',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:kind,revision:rev,version:viewVersion?.id,description:description||changeSummary()})});await load();setViewVersion(null);setNotice(kind==='publish'?'Published. Your previous version is saved in History.':kind==='restore'?'Previous version restored as a draft. Preview it, then Publish when ready.':'Draft discarded. Published content is restored.')}setConfirmAction('')}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
 function changeSummary(){if(!draft)return 'Website update';try{const old=JSON.parse(published);return Object.keys(draft).filter(k=>JSON.stringify((draft as any)[k])!==JSON.stringify(old[k])).map(k=>({hero:'Welcome',about:'About',sections:'Section order / visibility',services:'Services & pricing',faqs:'FAQs',portfolio:'Before & after',areas:'Service areas',promotion:'Announcement',contact:'Business contact'}[k]||k)).join(', ')||'Website update'}catch{return 'Website update'}}
 async function upload(file:File){setBusy(true);try{const form=new FormData();form.set('file',file);form.set('category',mediaCategory);const thumb=await thumbnail(file);if(thumb)form.set('thumbnail',thumb,'thumbnail.jpg');const d=await req('/api/owner/website/media',{method:'POST',body:form});await loadMedia();if(picker){picker(d.id);setPicker(null)}setNotice('Original photo saved. It becomes public only when used in a published section.')}catch(e){setNotice((e as Error).message)}finally{setBusy(false);if(uploadInput.current)uploadInput.current.value=''}}
 function choose(setter:(id:string)=>void,category='website'){setMediaCategory(category);setPicker(()=>setter)}
 function text(label:string,value:Words,setter:(v:Words)=>void,large=false){return <label className="block text-sm font-medium">{label}{large?<textarea rows={4} maxLength={2000} className={field} value={value[language]} onChange={e=>setter({...value,[language]:e.target.value})}/>:<input className={field} maxLength={2000} value={value[language]} onChange={e=>setter({...value,[language]:e.target.value})}/>}</label>}
 function imageControl(label:string,id:string,setter:(id:string)=>void,category='website'){return <div className="space-y-2"><p className="text-sm font-medium">{label}</p>{id&&<img className="h-36 w-full rounded-2xl object-cover" alt={label} src={'/api/owner/website/media/'+id+'?thumbnail=1'}/>}<div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>choose(setter,category)}>{id?'Replace photo':'Choose photo'}</button>{id&&<button className={btn} onClick={()=>setter('')}>Remove from draft</button>}</div></div>}
 const service=draft?.services.find(s=>s.id===serviceId);
 function mediaGrid(select=false){return <><div className="flex flex-wrap gap-2"><select aria-label="Photo category" className={field+' !mt-0 !w-auto'} value={mediaCategory} onChange={e=>setMediaCategory(e.target.value)}><option value="website">Website photos</option><option value="before-after">Before / after</option><option value="owner">Owner photo</option></select><button className={primary} disabled={busy} onClick={()=>uploadInput.current?.click()}>Upload photo</button></div><p className="text-sm text-zinc-600">Your original file stays unchanged. Up to 25 MB per photo.</p><div className="grid grid-cols-2 gap-3">{media.filter(m=>(includeArchived||!m.archived)&&m.category===mediaCategory).map(m=><div key={m.id} className="min-w-0 space-y-2 rounded-2xl border p-3"><button className="w-full" disabled={!select} onClick={()=>{picker?.(m.id);setPicker(null)}}>{m.has_thumbnail?<img className="h-28 w-full rounded-xl object-cover" alt={m.name} src={'/api/owner/website/media/'+m.id+'?thumbnail=1'}/>:<span className="flex h-28 items-center justify-center rounded-xl bg-[#edf2ee] text-sm">Original photo</span>}<span className="mt-2 block break-words text-left text-sm">{m.name}</span></button>{select?<button className={btn+' w-full'} onClick={()=>{picker?.(m.id);setPicker(null)}}>Use photo</button>:<><a className="block py-2 text-sm underline" href={'/api/owner/website/media/'+m.id} target="_blank" rel="noreferrer">View original</a><button className={btn} onClick={async()=>{if(!confirm(m.archived?'Restore this photo?':'Archive this photo from the picker? Published versions keep their photos.'))return;try{await req('/api/owner/website/media',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:m.id,archived:!m.archived})});await loadMedia()}catch(e){setNotice((e as Error).message)}}}>{m.archived?'Restore':'Archive'}</button></>}</div>)}</div>{!media.some(m=>!m.archived&&m.category===mediaCategory)&&<p className="rounded-2xl bg-[#f1f4ef] p-4 text-sm">No photos in this category yet.</p>}<details><summary className="cursor-pointer py-3 text-sm">More options</summary><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/>Show archived photos</label><a className="block py-3 text-sm underline" href="/owner/bookings">Private customer / job photos →</a><p className="text-sm text-zinc-500">Job photos are kept in their customer files and are never added here automatically.</p></details></>}
 if(!draft)return <div className="p-6"><h1 className="text-3xl font-semibold">Website Editor</h1><p className="mt-4">{notice||'Loading your website…'}</p></div>;
 return <div className="mx-auto max-w-7xl p-4 md:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">Your website, your way.</h1><p className="mt-2 text-sm text-zinc-600">{dirty?'Unsaved changes':pending?'Saved draft · not published':'Published website'} · Changes stay private until you publish.</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||!dirty} className={btn} onClick={()=>action('save')}>Save draft</button><button disabled={busy||!pending} className={primary} onClick={()=>{setDescription(changeSummary());setConfirmAction('publish')}}>Publish changes</button></div></div>{notice&&<p role="status" className="my-4 rounded-2xl bg-[#dcece4] p-4 text-sm">{notice}</p>}<nav className="my-5 flex flex-wrap gap-2">{[['website','Website'],['services','Services & Pricing'],['media','Media Library'],['promotions','Announcement']].map(([id,label])=><button key={id} className={panel===id?primary:btn} onClick={()=>{setPanel(id);setShowPreview(false)}}>{label}</button>)}<details className="relative"><summary className={btn+' cursor-pointer list-none'}>More options</summary><div className="absolute right-0 z-10 mt-2 w-52 rounded-2xl border bg-white p-2 shadow-lg">{[['history','Version history'],['contact','Business contact']].map(([id,label])=><button className="block min-h-11 w-full rounded-xl p-3 text-left text-sm" key={id} onClick={()=>{setPanel(id);setShowPreview(false)}}>{label}</button>)}<button disabled={!pending||busy} className="min-h-11 w-full p-3 text-left text-sm text-red-700" onClick={()=>setConfirmAction('discard')}>Discard draft</button></div></details></nav><div className="mb-4 flex flex-wrap gap-2"><button className={btn+' lg:hidden'} onClick={()=>setShowPreview(!showPreview)}>{showPreview?'Back to editing':'Preview website'}</button><label className="flex items-center gap-2 text-sm">Editing language<select className={btn} value={language} onChange={e=>setLanguage(e.target.value as any)}><option value="en">English</option><option value="es">Español</option></select></label></div>
 <div className="grid min-w-0 gap-6 lg:grid-cols-[minmax(300px,440px)_minmax(0,1fr)]"><section className={(showPreview?'hidden lg:block ':'')+'min-w-0 space-y-5 rounded-3xl bg-white p-5'}>
 {panel==='website'&&<><p className="text-sm text-zinc-600">Choose a section or tap it in the preview.</p><details open={false}><summary className="cursor-pointer py-2 font-semibold">Arrange & show sections</summary><div className="mt-3 space-y-2">{draft.sections.map((item,i)=><div key={item.id} draggable onDragStart={()=>drag.current=i} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag.current===null)return;const from=drag.current;change(d=>{const [m]=d.sections.splice(from,1);d.sections.splice(i,0,m)});drag.current=null}} className="flex flex-wrap items-center gap-2 rounded-2xl border p-3"><button className="min-h-11 flex-1 text-left text-sm font-semibold" onClick={()=>setSection(item.id)}>{sectionNames[item.id]}</button><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" disabled={item.id==='hero'} checked={item.visible} onChange={e=>change(d=>{d.sections[i].visible=e.target.checked})}/>Show</label><button aria-label={'Move '+sectionNames[item.id]+' up'} disabled={i===0} className={btn} onClick={()=>move(i,-1)}>↑</button><button aria-label={'Move '+sectionNames[item.id]+' down'} disabled={i===draft.sections.length-1} className={btn} onClick={()=>move(i,1)}>↓</button></div>)}</div><p className="mt-2 text-sm text-zinc-500">Drag on desktop, or use the arrows. Hidden sections keep their content.</p></details><label className="block text-sm">Section<select className={field} value={section} onChange={e=>setSection(e.target.value as any)}>{Object.entries(sectionNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 {section==='hero'&&<>{text('Heading',draft.hero.heading,v=>change(d=>{d.hero.heading=v}),true)}{text('Description',draft.hero.body,v=>change(d=>{d.hero.body=v}),true)}{text('Button wording',draft.hero.button,v=>change(d=>{d.hero.button=v}))}{imageControl('Welcome photo',draft.hero.photo,id=>change(d=>{d.hero.photo=id}))}<details><summary className="cursor-pointer py-3 text-sm">More options</summary>{text('Small introductory line',draft.hero.eyebrow,v=>change(d=>{d.hero.eyebrow=v}))}</details></>}
 {section==='about'&&<>{text('Heading',draft.about.heading,v=>change(d=>{d.about.heading=v}))}{text('About you',draft.about.body,v=>change(d=>{d.about.body=v}),true)}{imageControl('Your uniform photo',draft.about.photo,id=>change(d=>{d.about.photo=id}),'owner')}</>}
 {section==='services'&&<button className={primary} onClick={()=>setPanel('services')}>Open Services & Pricing</button>}
 {section==='areas'&&<>{text('Areas you serve',draft.areas,v=>change(d=>{d.areas=v}),true)}<p className="text-sm text-zinc-500">Website wording only. Existing travel and phone-confirmation rules stay protected.</p></>}
 {section==='faq'&&<>{draft.faqs.map((f,i)=><details key={i} className="rounded-2xl border p-4"><summary className="cursor-pointer min-h-11">{f.question[language]||'New question'}</summary><div className="space-y-3">{text('Question',f.question,v=>change(d=>{d.faqs[i].question=v}))}{text('Answer',f.answer,v=>change(d=>{d.faqs[i].answer=v}),true)}<button className={btn} onClick={()=>{if(confirm('Remove this question from the draft? Published versions keep it.'))change(d=>{d.faqs.splice(i,1)})}}>Remove question</button></div></details>)}<button disabled={draft.faqs.length>=20} className={btn} onClick={()=>change(d=>{d.faqs.push({id:crypto.randomUUID(),question:{en:'',es:''},answer:{en:'',es:''}})})}>+ Add question</button></>}
 {section==='portfolio'&&<>{draft.portfolio.map((p,i)=><details key={i} className="rounded-2xl border p-4"><summary className="cursor-pointer min-h-11">{p.caption[language]||'Before / after pair '+(i+1)}</summary><div className="space-y-4">{imageControl('Before photo',p.before,id=>change(d=>{d.portfolio[i].before=id}),'before-after')}{imageControl('After photo',p.after,id=>change(d=>{d.portfolio[i].after=id}),'before-after')}{text('Caption',p.caption,v=>change(d=>{d.portfolio[i].caption=v}))}<button className={btn} onClick={()=>{if(confirm('Remove this pair from the draft? Originals and versions stay saved.'))change(d=>{d.portfolio.splice(i,1)})}}>Remove pair</button></div></details>)}<button disabled={draft.portfolio.length>=12} className={btn} onClick={()=>change(d=>{d.portfolio.push({id:crypto.randomUUID(),before:'',after:'',caption:{en:'',es:''}})})}>+ Add before / after pair</button><p className="text-sm text-zinc-500">Use business photos you have permission to publish. No customer details are included.</p></>}
 </>}
 {panel==='services'&&service&&<><label className="block text-sm">Service<select className={field} value={serviceId} onChange={e=>{setServiceId(e.target.value);setUnlock(false)}}>{draft.services.map(s=><option key={s.id} value={s.id}>{s.name.en}</option>)}</select></label>{text('Service name',service.name,v=>change(d=>{d.services.find(s=>s.id===serviceId)!.name=v}))}{text('Description',service.description,v=>change(d=>{d.services.find(s=>s.id===serviceId)!.description=v}),true)}{imageControl('Service photo',service.photo,id=>change(d=>{d.services.find(s=>s.id===serviceId)!.photo=id}))}<p className="rounded-2xl bg-[#f1f4ef] p-4">Displayed range: <b>{serviceRange(service)}</b></p><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={service.active} onChange={e=>change(d=>{d.services.find(s=>s.id===serviceId)!.active=e.target.checked})}/>Show this service</label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={service.bookable} onChange={e=>change(d=>{d.services.find(s=>s.id===serviceId)!.bookable=e.target.checked})}/>Accept booking requests</label><details><summary className="cursor-pointer py-3 font-semibold">Pricing & more options</summary><p className="my-3 text-sm text-zinc-600">Changes apply to new estimates after publishing. Saved jobs and invoices keep their agreed amounts. Equipment, condition adjustments, travel rules and calculations stay protected.</p><label className="flex min-h-11 items-start gap-3 text-sm"><input className="mt-1" type="checkbox" checked={unlock} onChange={e=>setUnlock(e.target.checked)}/>Unlock pricing controls for this service</label>{Object.entries({base:'Standard price',...(serviceId==='patio'?{small:'Small patio',large:'Large patio'}:{}),...(['whole','exterior'].includes(serviceId)?{twoStory:'Two-story price'}:{}),...(serviceId!=='whole'?{bundle:'Same-visit add-on price'}:{}),...(serviceId==='patio'?{bundleLarge:'Large patio add-on'}:{}),...(serviceId==='exterior'?{bundleTwoStory:'Two-story add-on'}:{}),minimum:'Minimum standalone price',...(['driveway','walkways','commercial'].includes(serviceId)?{rangeExtra:'Upper-range allowance (display only)'}:{})}).map(([key,label])=><label key={key} className="mt-3 block text-sm">{label} ($)<input type="number" min="0" max="100000" step=".01" disabled={!unlock} className={field} value={(service.prices as any)[key]} onChange={e=>change(d=>{(d.services.find(s=>s.id===serviceId)!.prices as any)[key]=Number(e.target.value)})}/></label>)}</details></>}
 {panel==='media'&&mediaGrid()}
 {panel==='promotions'&&<><h2 className="text-xl font-semibold">A simple announcement</h2><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={draft.promotion.enabled} onChange={e=>change(d=>{d.promotion.enabled=e.target.checked})}/>Show announcement</label>{text('Message',draft.promotion.message,v=>change(d=>{d.promotion.message=v}),true)}<p className="text-sm text-zinc-500">Announcement text does not automatically discount estimates. Change service pricing separately if needed.</p><details><summary className="cursor-pointer py-3">Dates & placement</summary><div className="space-y-3">{[['start','Start date (optional)'],['end','End date (optional)']].map(([key,label])=><label key={key} className="block text-sm">{label}<input type="date" className={field} value={(draft.promotion as any)[key]} onChange={e=>change(d=>{(d.promotion as any)[key]=e.target.value})}/></label>)}<label className="block text-sm">Placement<select className={field} value={draft.promotion.placement} onChange={e=>change(d=>{d.promotion.placement=e.target.value as any})}><option value="top">Above welcome</option><option value="below">Below welcome</option></select></label><p className="text-sm text-zinc-500">Dates use Los Angeles time. A scheduled announcement appears only during its date range.</p></div></details></>}
 {panel==='contact'&&<><h2 className="text-xl font-semibold">Business contact</h2><p className="text-sm text-zinc-600">One set of contact details for the website and new documents. These edits take effect when you Publish. Your private mileage base and login are not changed.</p>{Object.entries({name:'Business name',ownerName:'Owner name',phone:'Business phone',email:'Business email',website:'Website / domain'}).map(([key,label])=><label key={key} className="block text-sm">{label}<input className={field} value={(draft.contact as any)[key]} onChange={e=>change(d=>{(d.contact as any)[key]=e.target.value})}/></label>)}<a className="block py-3 text-sm underline" href="/owner/settings">Other business settings →</a></>}
 {panel==='history'&&<><h2 className="text-xl font-semibold">Version history</h2><p className="text-sm text-zinc-600">Restore brings a version into Draft. The live site changes only when you Publish.</p>{versions.map(v=><div key={v.id} className="rounded-2xl border p-4"><b className="block break-words">{v.description}</b><p className="my-2 text-sm text-zinc-500">{new Date(v.created_at).toLocaleString()}</p><button className={btn} onClick={async()=>{try{const d=await req('/api/owner/website?version='+v.id);setViewVersion({...d,id:v.id});setShowPreview(true)}catch(e){setNotice((e as Error).message)}}}>Preview version</button></div>)}</>}
 </section><aside className={(showPreview?'':'hidden lg:block ')+'min-w-0'}><div className="mb-3 flex flex-wrap gap-2">{['mobile','desktop'].map(m=><button key={m} className={previewMode===m?primary:btn} onClick={()=>setPreviewMode(m)}>{m==='mobile'?'Mobile preview':'Desktop preview'}</button>)}</div>{viewVersion&&<div className="mb-3 space-y-2 rounded-2xl bg-white p-4"><b>{viewVersion.description}</b><div className="flex flex-wrap gap-2"><button className={primary} onClick={()=>setConfirmAction('restore')}>Restore as draft</button><button className={btn} onClick={()=>setViewVersion(null)}>Back to current draft</button></div></div>}<p className="mb-3 text-sm text-zinc-600">{viewVersion?'Previous published version':'Private preview · tap a section to edit'}</p><div ref={previewHost} className="min-w-0 overflow-hidden rounded-3xl border bg-white" style={{height:Math.min(820,Math.max(420,(previewMode==='mobile'?844:900)*Math.min(1,previewWidth/(previewMode==='mobile'?390:1200))))}}><iframe ref={frame} title="Private website preview" src="/legacy/?editor=1" onLoad={sendPreview} style={{width:previewMode==='mobile'?390:1200,height:previewMode==='mobile'?844:900,border:0,transformOrigin:'top left',transform:`scale(${Math.min(1,previewWidth/(previewMode==='mobile'?390:1200))})`}}/></div></aside></div>
 <input ref={uploadInput} type="file" hidden accept="image/jpeg,image/png,image/webp,image/avif,image/heic,image/heif" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0])}}/>
 <Dialog open={!!picker} onOpenChange={v=>{if(!v)setPicker(null)}}><DialogContent className="max-h-[90dvh] overflow-y-auto rounded-3xl bg-white text-[#173b32] sm:max-w-xl"><DialogTitle>Choose a business photo</DialogTitle><DialogDescription>Private job photos stay in their customer files.</DialogDescription>{notice&&<p role="status" className="text-sm">{notice}</p>}{mediaGrid(true)}</DialogContent></Dialog>
 <Dialog open={!!confirmAction} onOpenChange={v=>{if(!v&&!busy)setConfirmAction('')}}><DialogContent className="rounded-3xl bg-white text-[#173b32]"><DialogTitle>{confirmAction==='publish'?'Publish these changes?':confirmAction==='restore'?'Restore this version as a draft?':'Discard this draft?'}</DialogTitle><DialogDescription>{confirmAction==='publish'?'Visitors and new estimates will use the published content. Existing jobs and invoices remain unchanged.':confirmAction==='restore'?'This replaces your current draft. Your published website and previous versions stay saved.':'Unsaved and saved draft edits will be replaced with the published website.'}</DialogDescription>{confirmAction==='publish'&&<label className="text-sm">Short description for history<input className={field} maxLength={200} value={description} onChange={e=>setDescription(e.target.value)}/></label>}<div className="flex flex-wrap gap-2"><button disabled={busy} className={primary} onClick={()=>action(confirmAction)}>{busy?'Saving…':confirmAction==='publish'?'Publish now':confirmAction==='restore'?'Restore draft':'Discard draft'}</button><button disabled={busy} className={btn} onClick={()=>setConfirmAction('')}>Keep editing</button></div></DialogContent></Dialog>
 </div>;
}
