import {businessSettings} from '../../../../lib/business';
import {rawDb} from "../../../../db";import {forbidden,ownerAuthorized} from "../../owner-auth";import {isoDate,failure} from "../../records-utils";
import {mileageSummary} from '../../../../lib/mileage-summary';
// Prefix formula-like text so a customer-supplied name cannot execute in a spreadsheet.
const cell=(v:unknown)=>{let s=String(v??"");if(typeof v!=="number"&&/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const u=new URL(r.url),year=u.searchParams.get("year")||String(new Date().getFullYear()),from=u.searchParams.get("from")||`${year}-01-01`,to=u.searchParams.get("to")||`${year}-12-31`,type=u.searchParams.get("type")||"tax";if(!isoDate(from)||!isoDate(to)||from>to||!["tax","bank","backup"].includes(type))return Response.json({error:"Choose a valid report period."},{status:400});const contact=await businessSettings(),db=rawDb();const [payments,costs,trips,work]=await Promise.all([
 db.prepare("SELECT j.*, c.first_name,c.last_name FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE substr(j.paid_at,1,10) BETWEEN ? AND ? ORDER BY j.paid_at").bind(from,to).all<any>(),
 db.prepare("SELECT * FROM expenses WHERE expense_date BETWEEN ? AND ? ORDER BY expense_date").bind(from,to).all<any>(),
 db.prepare("SELECT *, round(end_odometer-start_odometer,1) AS miles FROM mileage WHERE trip_date BETWEEN ? AND ? ORDER BY trip_date").bind(from,to).all<any>(),
 db.prepare("SELECT j.*,c.first_name,c.last_name FROM jobs j JOIN customers c ON c.id=j.customer_id ORDER BY j.created_at").all<any>()]);
 const [auto,vehicles,usage,links]=await Promise.all([db.prepare('SELECT t.*,v.nickname AS vehicle,v.plate,v.vin FROM trip_records t LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE trip_date BETWEEN ? AND ? ORDER BY trip_date').bind(from,to).all<any>(),db.prepare('SELECT * FROM vehicles').all<any>(),db.prepare("SELECT m.*,s.name,s.unit FROM supply_movements m JOIN supplies s ON s.id=m.supply_id WHERE movement_date BETWEEN ? AND ? ORDER BY movement_date").bind(from,to).all<any>(),db.prepare('SELECT l.trip_id,l.job_id,c.first_name,c.last_name FROM trip_jobs l JOIN trip_records t ON t.id=l.trip_id JOIN jobs j ON j.id=l.job_id JOIN customers c ON c.id=j.customer_id WHERE t.trip_date BETWEEN ? AND ?').bind(from,to).all<any>()]);const summary=mileageSummary(auto.results,[],from,to),confirmed=auto.results.filter(x=>x.status==='confirmed'),extraMiles=summary.total,deduction=confirmed.reduce((n,x)=>n+(x.method==='standard'&&x.rate!==null&&x.eligible_miles!==null?x.rate*x.eligible_miles:0),0);
 const paid=payments.results.reduce((n,x)=>n+Number(x.paid_amount||0),0),spent=costs.results.reduce((n,x)=>n+Number(x.amount),0),distance=trips.results.reduce((n,x)=>n+x.miles,0)+extraMiles;
 const lines:any[][]=[[contact.name+" — owner-prepared business records"],["Business contact",contact.ownerName,contact.phone,contact.email,contact.website],["Report",type,"From",from,"Through",to],["Recorded payments",paid],["Recorded expenses",spent],["Payments minus expenses (not taxable income)",Math.round((paid-spent)*100)/100],["Job mileage reference (business eligibility requires review)",distance],["Trips missing distance, excluded from total",summary.missing],["Maps references included",summary.estimated],["Estimated standard-mileage deduction — separate from expenses",Math.round(deduction*100)/100],["Mileage rate source","https://www.irs.gov/tax-professionals/standard-mileage-rates"],["These records do not establish deductibility or replace filed tax returns. Verify against receipts and bank statements."],[],["RECORDED PAYMENTS"],["Received date","Job ID","Customer","Service","Amount","Payment method"],...payments.results.map(x=>[x.paid_at,x.id,`${x.first_name} ${x.last_name}`,x.service,x.paid_amount,x.payment_method])];
 if(type!=="bank")lines.push([],["EXPENSES"],["Date","Vendor","Category","Purpose","Amount","Payment method","Job ID","Receipt"],...costs.results.map(x=>[x.expense_date,x.vendor,x.category,x.business_purpose,x.amount,x.payment_method,x.job_id,x.receipt_object_key?`/api/owner/receipts/${x.id}`:"No receipt attached"]),[],["MILEAGE LOG — no deduction calculated"],["Date","Vehicle","From","To","Purpose","Odometer start","Odometer end","Miles","Job ID"],...trips.results.map(x=>[x.trip_date,x.vehicle,x.origin,x.destination,x.purpose,x.start_odometer,x.end_odometer,x.miles,x.job_id]));
 if(type!=="bank")lines.push([],["JOB TRIPS — each shared route counted once"],["Trip ID","Date","Vehicle","Plate","Route","Purpose","Status","Estimated miles","Owner-entered reference miles","Eligible miles","Method","Rate","Estimated deduction","Confirmed at"],...auto.results.map(x=>[x.id,x.trip_date,x.vehicle,x.plate,JSON.parse(x.route_json).join(' → '),x.purpose,x.status,x.estimated_miles,x.actual_miles,x.eligible_miles,x.method,x.rate,x.status==='confirmed'&&x.method==='standard'&&x.rate!==null&&x.eligible_miles!==null?Math.round(x.rate*x.eligible_miles*100)/100:'Not calculated',x.confirmed_at]),[],["TRIP CUSTOMER LINKS — shared trips are not separate mileage entries"],["Trip ID","Job ID","Customer"],...links.results.map(x=>[x.trip_id,x.job_id,`${x.first_name} ${x.last_name}`]),[],["VEHICLES"],["ID","Nickname","Year / make / model","Plate","VIN","Starting odometer","Business use start","Archived"],...vehicles.results.map(x=>[x.id,x.nickname,x.details,x.plate,x.vin,x.starting_odometer,x.start_date,x.archived]),[],["SUPPLY MOVEMENTS — allocation only, do not add to expenses again"],["Date","Supply","Unit","Quantity","Unit cost","Kind","Job ID","Purchase expense ID","Note"],...usage.results.map(x=>[x.movement_date,x.name,x.unit,x.quantity,x.unit_cost,x.kind,x.job_id,x.expense_id,x.note]));
 if(type!=="tax")lines.push([],["WORK ORDERS — estimates are not receipts of payment"],["Date","Job ID","Customer","Service","Status","Quoted/invoiced amount"],...work.results.filter(x=>{const date=new Date(x.scheduled_date);const s=Number.isFinite(+date)?date.toISOString().slice(0,10):x.created_at.slice(0,10);return s>=from&&s<=to}).map(x=>[x.scheduled_date,x.id,`${x.first_name} ${x.last_name}`,x.service,x.status,x.price]));
 return new Response('\ufeff'+lines.map(x=>x.map(cell).join(',')).join('\r\n'),{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="pressure-up-${type}-${from}-to-${to}.csv"`,"Cache-Control":"private, no-store"}});
 }catch(e){return failure(e)}}
