import {rawDb} from '../../../../db';
import {ownerAuthorized,forbidden} from '../../owner-auth';
import {businessSettings} from '../../../../lib/business';
import {mileageSummary} from '../../../../lib/mileage-summary';
import {esc,table,printResponse} from '../../../../lib/print-records';
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{
 const q=new URL(r.url).searchParams,year=q.get('year')||String(new Date().getFullYear());if(!/^(19|20|21)\d{2}$/.test(year))return Response.json({error:'Choose a valid year.'},{status:400});
 const db=rawDb(),from=year+'-01-01',to=year+'-12-31';const [income,expenses,trips,old,links]=await Promise.all([
 db.prepare("SELECT j.id AS job_id,j.customer_id,j.paid_at,j.paid_amount,j.payment_method,j.service,c.first_name||' '||c.last_name AS customer FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE substr(j.paid_at,1,10) BETWEEN ? AND ? ORDER BY j.paid_at").bind(from,to).all<any>(),
 db.prepare("SELECT e.*,c.first_name||' '||c.last_name AS customer,j.customer_id FROM expenses e LEFT JOIN jobs j ON j.id=e.job_id LEFT JOIN customers c ON c.id=j.customer_id WHERE e.expense_date BETWEEN ? AND ? ORDER BY e.expense_date").bind(from,to).all<any>(),
 db.prepare('SELECT t.*,v.nickname AS vehicle FROM trip_records t LEFT JOIN vehicles v ON v.id=t.vehicle_id WHERE trip_date BETWEEN ? AND ? ORDER BY trip_date').bind(from,to).all<any>(),
 db.prepare('SELECT *,round(end_odometer-start_odometer,1) AS miles FROM mileage WHERE trip_date BETWEEN ? AND ?').bind(from,to).all<any>(),
 db.prepare("SELECT l.*,c.first_name||' '||c.last_name AS customer FROM trip_jobs l JOIN trip_records t ON t.id=l.trip_id JOIN jobs j ON j.id=l.job_id JOIN customers c ON c.id=j.customer_id WHERE trip_date BETWEEN ? AND ?").bind(from,to).all<any>()]);
 const cents=(n:any)=>Math.round(Number(n||0)*100),received=income.results.reduce((n:number,x:any)=>n+cents(x.paid_amount),0)/100,spent=expenses.results.reduce((n:number,x:any)=>n+cents(x.amount),0)/100,categories:Record<string,number>={};for(const e of expenses.results)categories[e.category]=(categories[e.category]||0)+cents(e.amount);for(const k of Object.keys(categories))categories[k]/=100;
 const mileage=mileageSummary(trips.results,old.results,from,to),summary={year,received,expenses:spent,profit:Math.round((received-spent)*100)/100,miles:mileage.total,missing:mileage.missing,estimated:mileage.estimated,categories};
 if(q.get('format')==='pdf'){const b=await businessSettings(),money=(n:number)=>'$'+n.toFixed(2);return printResponse('Tax summary — '+year,`<p>${esc(b.name)} · ${esc(b.ownerName)} · ${esc(year)}</p>${table(['Money received','Recorded expenses','Recorded profit','Business mileage reference'],[[money(received),money(spent),money(summary.profit),mileage.total+' mi']])}<h2>Expenses by category</h2>${table(['Category','Recorded amount'],Object.entries(categories).map(([k,v])=>[k,money(v)]))}<p>Owner-prepared figures based on saved records, not a filed tax return or tax/legal advice. Recorded profit is receipts minus recorded expenses, not taxable income. Mileage eligibility requires review; mileage deductions are not added to expenses here. ${mileage.missing} trips have no distance and are excluded. ${mileage.estimated} distances are route estimates.</p><h2>Payments supporting this summary</h2>${table(['Date','Customer / job','Method','Received'],income.results.map((x:any)=>[x.paid_at,x.customer+' / '+x.job_id,x.payment_method,money(Number(x.paid_amount))]))}<p>Export Detailed Records for expense receipts, job associations, vehicle records and individual trips. Supporting records remain in their customer files.</p>`,r)}
 return Response.json({summary,income:income.results,expenses:expenses.results.map(({receipt_object_key,...e}:any)=>({...e,receipt:receipt_object_key?'/api/owner/receipts/'+e.id:null})),trips:mileage.rows,legacy:mileage.legacy,links:links.results},{headers:{'Cache-Control':'private, no-store'}})
 }catch{return Response.json({error:'Could not load the tax summary.'},{status:500})}}
