import {env} from '@/lib/runtime-env';
import {rawDb} from "../../../../db";
import {forbidden,ownerAuthorized} from "../../owner-auth";
import {clean,isoDate,moneyValue,failure} from "../../records-utils";
import{sha256,duplicateReceipts}from'../../../../lib/receipt-records';
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{return Response.json((await rawDb().prepare("SELECT * FROM expenses ORDER BY expense_date DESC, created_at DESC").all()).results,{headers:{"Cache-Control":"no-store"}})}catch(e){return failure(e)}}
export async function POST(r:Request){if(!(await ownerAuthorized(r)))return forbidden();let key:string|null=null;try{
 if(Number(r.headers.get('content-length')||0)>11*1024*1024)return Response.json({error:'Receipt too large.'},{status:413});
 const f=await r.formData(),id=crypto.randomUUID(),amount=moneyValue(f.get("amount")),date=f.get("expenseDate"),vendor=clean(f.get("vendor")),purpose=clean(f.get("businessPurpose")),job=clean(f.get("jobId"))||null;
 if(!isoDate(date)||!vendor||!purpose||amount<=0)return Response.json({error:"Enter a date, amount, vendor, and business purpose."},{status:400});
 if(job&&!await rawDb().prepare("SELECT id FROM jobs WHERE id=?").bind(job).first())return Response.json({error:"Choose an existing job."},{status:400});
 const submission=clean(f.get('submissionKey'),80);if(submission){const existing=await rawDb().prepare('SELECT id FROM expenses WHERE submission_key=?').bind(submission).first<any>();if(existing)return Response.json({ok:true,id:existing.id},{status:200})}
 const receipt=f.get("receipt"),hasReceipt=receipt instanceof File&&receipt.size>0,receiptBytes=hasReceipt?await (async()=>{if(receipt.size>10*1024*1024||!['image/jpeg','image/png','image/webp','application/pdf'].includes(receipt.type))throw Error('Use a JPG, PNG, WebP, or PDF receipt up to 10 MB.');return receipt.arrayBuffer()})():null,sha=receiptBytes?await sha256(receiptBytes):'',dhash=/^[a-f0-9]{16}$/.test(String(f.get('dhash')))?String(f.get('dhash')):'';
 let details:any={};if(f.get('receiptDetails')){if(String(f.get('receiptDetails')).length>40000)return Response.json({error:'Receipt notes are too long.'},{status:400});try{details=JSON.parse(String(f.get('receiptDetails')));if(!details||typeof details!=='object'||Array.isArray(details))throw Error('Invalid receipt details')}catch{return Response.json({error:'Review the receipt details again.'},{status:400})}if(f.get('receiptReviewed')!=='yes')return Response.json({error:'Confirm the receipt details before saving.'},{status:400});details={vendor,date,total:amount,subtotal:details.subtotal==null?null:moneyValue(details.subtotal),tax:details.tax==null?null:moneyValue(details.tax),lineItems:(Array.isArray(details.lineItems)?details.lineItems:[]).slice(0,40).map((x:any)=>({description:clean(x?.description,150),amount:moneyValue(x?.amount)})),method:clean(details.method,80),reviewedAt:new Date().toISOString()}}
 const duplicates=await duplicateReceipts({vendor,date:String(date),amount,sha,dhash});if(duplicates.matches.length&&f.get('duplicateToken')!==duplicates.token)return Response.json({error:'This may already be recorded. Review the matching receipts before saving another expense.',duplicates:duplicates.matches,duplicateToken:duplicates.token},{status:409});
 if(receipt instanceof File&&receipt.size){if(receipt.size>10*1024*1024||!["image/jpeg","image/png","image/webp","application/pdf"].includes(receipt.type))return Response.json({error:"Use a JPG, PNG, WebP, or PDF receipt up to 10 MB."},{status:400});key=`receipts/${id}/${crypto.randomUUID()}`;await env.BUCKET.put(key,receiptBytes!,{httpMetadata:{contentType:receipt.type}});}
 const inserted=await rawDb().prepare("INSERT INTO expenses (id,amount,vendor,category,expense_date,payment_method,business_purpose,job_id,receipt_object_key,receipt_sha256,receipt_dhash,receipt_details,submission_key) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ? IS NULL OR NOT EXISTS (SELECT 1 FROM expenses WHERE submission_key=?)").bind(id,amount,vendor,clean(f.get("category")),date,clean(f.get("paymentMethod")),purpose,job,key,sha||null,dhash||null,JSON.stringify(details),submission||null,submission||null,submission||null).run();if(!inserted.meta.changes){if(key)await env.BUCKET.delete(key);const existing=await rawDb().prepare('SELECT id FROM expenses WHERE submission_key=?').bind(submission).first<any>();return Response.json({ok:true,id:existing.id})}return Response.json({ok:true,id},{status:201});
 }catch(e){if(key)await env.BUCKET.delete(key).catch(()=>{});return failure(e)}}
