import {env} from '@/lib/runtime-env';
import {businessSettings} from './business';
import {rawDb} from '../db';
export async function siteUrl(){return (await businessSettings()).website.replace(/\/$/,'')}
export function connections(){const e=env as any;return {maps:!!e.GOOGLE_MAPS_API_KEY,sms:!!(e.TWILIO_ACCOUNT_SID&&e.TWILIO_AUTH_TOKEN&&e.TWILIO_FROM_NUMBER),email:!!(e.RESEND_API_KEY&&e.EMAIL_FROM),payments:false,photoAssessment:false}}
export function phone(v:string){const digits=v.replace(/\D/g,'');return '+'+(digits.length===10?'1'+digits:digits)}
export async function sendNotification(id:string){
 const db=rawDb(),n=await db.prepare('SELECT n.*,c.phone,c.email,c.consent FROM notifications n LEFT JOIN customers c ON c.id=n.customer_id WHERE n.id=?').bind(id).first<any>();
 if(!n)throw Error('Message not found.');if(!['draft','queued','connection needed','failed'].includes(n.status))return {status:n.status};
 const channel=n.channel,ready=connections();if(channel==='manual')return {status:'draft'};
 if(channel==='sms'&&!n.consent)throw Error('This customer has opted out of texts.');
 if((channel==='sms'&&!ready.sms)||(channel==='email'&&!ready.email)){await db.prepare("UPDATE notifications SET status='connection needed' WHERE id=?").bind(id).run();return {status:'connection needed'}}
 const claimed=await db.prepare("UPDATE notifications SET status='sending' WHERE id=? AND status IN ('draft','queued','connection needed','failed')").bind(id).run();if(!claimed.meta.changes)return {status:'sending'};
 const contact=await businessSettings(),e=env as any,to=n.destination||(channel==='sms'?phone(n.phone):n.email);let response:Response;
 try{if(channel==='sms'){response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${e.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:'Basic '+btoa(e.TWILIO_ACCOUNT_SID+':'+e.TWILIO_AUTH_TOKEN),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({To:to,From:e.TWILIO_FROM_NUMBER,Body:n.message,StatusCallback:(await siteUrl())+'/api/hooks/texts'}),signal:AbortSignal.timeout(12000)})}else if(channel==='email'){response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+e.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':id},body:JSON.stringify({from:e.EMAIL_FROM,to:[to],subject:contact.name+' · Your appointment',reply_to:contact.email,text:n.message}),signal:AbortSignal.timeout(12000)})}else throw Error('Unsupported delivery method.');
 if(!response.ok){await db.prepare("UPDATE notifications SET status='failed' WHERE id=?").bind(id).run();return {status:'failed'}}const result=await response.json() as any;await db.prepare("UPDATE notifications SET status='accepted by provider',provider_id=?,destination=?,sent_at=? WHERE id=?").bind(result.sid||result.id||null,to,new Date().toISOString(),id).run();return {status:'accepted by provider'};
 }catch{await db.prepare("UPDATE notifications SET status='delivery uncertain' WHERE id=?").bind(id).run();return {status:'delivery uncertain'}}
}
export async function queueMessage(job:any,type:string,message:string,channel='email',destination:string|null=null,id:string=crypto.randomUUID()){
 await rawDb().prepare('INSERT OR IGNORE INTO notifications (id,job_id,customer_id,type,channel,status,message,destination) VALUES (?,?,?,?,?,?,?,?)').bind(id,job.id,job.customer_id,type,channel,'draft',message,destination).run();const result=await sendNotification(id);return {id,...result};
}
export async function bookingMessages(jobId:string){const j=await rawDb().prepare('SELECT j.*,c.first_name,c.language FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE j.id=?').bind(jobId).first<any>();if(!j)return;const contact=await businessSettings(),link=(await siteUrl())+'/manage/'+j.manage_token;const text=j.language==='Spanish'?`Hola ${j.first_name}, recibimos tu solicitud de ${contact.name} para ${j.scheduled_date}, ${j.arrival_window}. Estimado: $${j.price}. Tu cita está pendiente de confirmación. Detalles: ${link}`:`Hi ${j.first_name}, ${contact.name} received your request for ${j.scheduled_date}, ${j.arrival_window}. Estimate: $${j.price}. Your appointment is awaiting confirmation. Details: ${link}`;await queueMessage(j,'booking_received',text,'email',null,'booking-'+j.id);if(j.updates_opt_in)await queueMessage(j,'booking_received_sms',text,'sms',null,'booking-sms-'+j.id);await queueMessage(j,'owner_booking',`New ${contact.name} request: ${j.service}, ${j.scheduled_date}, $${j.price}. Open your dashboard: ${await siteUrl()}/owner/bookings?job=${j.id}`,'email',contact.email,'owner-booking-'+j.id)}
