import {rawDb} from '../db';
import {businessSettings} from './business';
export async function invoiceState(j:any){const row=await rawDb().prepare('SELECT * FROM invoice_records WHERE job_id=?').bind(j.id).first<any>();const issued=!row&&j.invoice_json!=='[]'?await rawDb().prepare("SELECT id FROM notifications WHERE job_id=? AND type='invoice' LIMIT 1").bind(j.id).first():null;if(row&&row.state==='None'&&j.invoice_json!=='[]')row.state='Draft';return row||{job_id:j.id,state:j.paid_at?'Paid':j.invoice_json==='[]'?'None':(j.status==='Invoice sent'||issued)?'Sent':'Draft',revision:1,token:''}}
export async function invoiceInfo(j:any){const m=await invoiceState(j),versions=await rawDb().prepare('SELECT id,revision,created_at FROM invoice_versions WHERE job_id=? ORDER BY revision DESC').bind(j.id).all();return {...m,state:j.paid_at?'Paid':m.state,number:j.id,versions:versions.results}}
export async function initializeInvoice(j:any){const initial=await invoiceState(j);await rawDb().prepare('INSERT OR IGNORE INTO invoice_records (job_id,state,revision,token,updated_at) VALUES (?,?,?,?,?)').bind(j.id,initial.state,1,crypto.randomUUID(),new Date().toISOString()).run();return invoiceState(j)}
export async function changeInvoice(j:any,m:any,change:{items?:string;price?:number;state:string;revision?:number;status?:string;snapshot?:any}){
 const db=rawDb(),token=crypto.randomUUID(),now=new Date().toISOString();
 const first=await db.prepare("UPDATE jobs SET invoice_json=?,price=?,status=? WHERE id=? AND paid_at IS NULL AND status!='Paid' AND invoice_json=? AND price=? AND status=? AND EXISTS (SELECT 1 FROM invoice_records WHERE job_id=? AND token=?)").bind(change.items??j.invoice_json,change.price??j.price,change.status??j.status,j.id,j.invoice_json,j.price,j.status,j.id,m.token).run();
 if(!first.meta.changes)throw Error('Invoice changed on another screen or a payment was recorded. Reload before trying again.');
 await db.prepare('UPDATE invoice_records SET state=?,revision=?,token=?,updated_at=? WHERE job_id=? AND token=?').bind(change.state,change.revision??m.revision,token,now,j.id,m.token).run();
 if(change.snapshot)await db.prepare('INSERT OR IGNORE INTO invoice_versions (id,job_id,revision,snapshot_json,created_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM invoice_records WHERE job_id=? AND token=?)').bind(crypto.randomUUID(),j.id,m.revision,JSON.stringify(change.snapshot),now,j.id,token).run();
 return invoiceState({...j,invoice_json:change.items??j.invoice_json});
}
export async function invoiceSnapshot(id:string){const j=await rawDb().prepare('SELECT j.*,c.first_name,c.last_name,CASE WHEN length(j.service_address)>0 THEN j.service_address ELSE c.address END AS address,c.email FROM jobs j JOIN customers c ON c.id=j.customer_id WHERE j.id=?').bind(id).first<any>();const b=await businessSettings();const {baseAddress,ownerPhotoKey,...contact}=b;return {job:j,contact}}
export async function freezeInvoice(j:any){if(j.invoice_json==='[]')throw Error('Save the invoice first.');let m=await initializeInvoice(j);if(j.paid_at){const snapshot=await invoiceSnapshot(j.id);await rawDb().prepare('INSERT OR IGNORE INTO invoice_versions (id,job_id,revision,snapshot_json,created_at) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),j.id,m.revision,JSON.stringify(snapshot),new Date().toISOString()).run();return {...m,state:'Paid'}}if(m.state==='Void')throw Error('This invoice is void.');const existing=await rawDb().prepare('SELECT id FROM invoice_versions WHERE job_id=? AND revision=?').bind(j.id,m.revision).first();if(m.state==='Sent'&&existing)return m;return changeInvoice(j,m,{state:'Sent',snapshot:await invoiceSnapshot(j.id)});}
