import {PDFDocument,StandardFonts,rgb} from 'pdf-lib';
export type PdfBlock={kind:'heading'|'text';text:string}|{kind:'table';rows:string[][]};
const plain=(text:unknown)=>String(text??'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&(?:amp|lt|gt|quot|#39|nbsp);/g,v=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'",'&nbsp;':' '}[v]!)).replace(/→/g,' to ').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'');
export function htmlBlocks(body:string):PdfBlock[]{const blocks:PdfBlock[]=[];for(const m of body.matchAll(/<(table|h[1-6]|p|li)\b[^>]*>([\s\S]*?)<\/\1>/gi)){if(m[1]==='table')blocks.push({kind:'table',rows:[...m[2].matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)].map(row=>[...row[1].matchAll(/<t[hd]\b[^>]*>([\s\S]*?)<\/t[hd]>/gi)].map(cell=>plain(cell[1])))});else blocks.push({kind:m[1][0]==='h'?'heading':'text',text:plain(m[2])})}return blocks}
export async function makePdf(title:string,blocks:PdfBlock[],contact:{name:string;ownerName:string;phone:string;email:string;website:string}){
 const pdf=await PDFDocument.create();pdf.setTitle(`${contact.name} - ${title}`);pdf.setAuthor(contact.ownerName);pdf.setCreator(contact.name);pdf.setCreationDate(new Date());const regular=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold),green=rgb(.09,.23,.19),muted=rgb(.35,.40,.38),width=612,height=792,margin=42,usable=width-margin*2;let page:any,y=0;
 const safe=(text:string)=>[...text].map(c=>{try{regular.encodeText(c);return c}catch{return c==='\n'?'\n':'?'}}).join('');
 function wrap(text:string,w:number,size:number,font=regular){const lines:string[]=[];for(const paragraph of safe(text).split('\n')){let line='';for(const word of paragraph.split(/\s+/)){if(!word)continue;for(const part of font.widthOfTextAtSize(word,size)>w?[...word]:[word]){const gap=line&&part===word?' ':'';if(font.widthOfTextAtSize(line+gap+part,size)>w){lines.push(line);line=part}else line+=gap+part}}lines.push(line)}return lines.length?lines:['']}
 function newPage(){page=pdf.addPage([width,height]);y=height-margin;page.drawText(safe(contact.name),{x:margin,y:y-18,size:20,font:bold,color:green});y-=37;for(const line of wrap(`${contact.ownerName} | ${contact.phone} | ${contact.email}`,usable,9)){page.drawText(line,{x:margin,y,size:9,font:regular,color:muted});y-=13}for(const line of wrap(contact.website,usable,9)){page.drawText(line,{x:margin,y,size:9,font:regular,color:muted});y-=13}y-=10;page.drawLine({start:{x:margin,y},end:{x:width-margin,y},color:green,thickness:1});y-=25;for(const line of wrap(title,usable,15,bold)){page.drawText(line,{x:margin,y,size:15,font:bold,color:green});y-=20}y-=8}
 function ensure(space:number){if(y-space<54)newPage()}
 newPage();for(const block of blocks){if(block.kind!=='table'){const size=block.kind==='heading'?12:10,font=block.kind==='heading'?bold:regular;ensure(40);if(block.kind==='heading')y-=8;for(const line of wrap(block.text,usable,size,font)){ensure(16);page.drawText(line,{x:margin,y,size,font,color:green});y-=15}y-=9;continue}
 if(!block.rows.length)continue;const cols=Math.max(...block.rows.map(r=>r.length)),cw=usable/cols,size=cols>4?8:10,lineHeight=12,head=block.rows[0];
 const renderRow=(row:string[],header=false)=>{const lines=Array.from({length:cols},(_,i)=>wrap(row[i]||'',cw-12,size,header?bold:regular));let offset=0;const count=Math.max(...lines.map(x=>x.length));while(offset<count){if(y-30<54){newPage();if(!header)renderRow(head,true)}const take=Math.min(count-offset,Math.max(1,Math.floor((y-60)/lineHeight))),rh=take*lineHeight+12;if(header)page.drawRectangle({x:margin,y:y-rh,width:usable,height:rh,color:rgb(.92,.95,.93)});for(let col=0;col<cols;col++)for(let n=0;n<take;n++){const text=lines[col][offset+n];if(text)page.drawText(text,{x:margin+col*cw+6,y:y-12-n*lineHeight,size,font:header?bold:regular,color:green})}y-=rh;page.drawLine({start:{x:margin,y},end:{x:width-margin,y},color:rgb(.82,.86,.83),thickness:.5});offset+=take}};
 renderRow(head,true);for(const row of block.rows.slice(1))renderRow(row);y-=16;
 }const pages=pdf.getPages();pages.forEach((p,i)=>p.drawText(`${i+1} / ${pages.length}`,{x:width-margin-45,y:25,size:9,font:regular,color:muted}));return pdf.save();
}
