import {rawDb} from '../db';
import {businessSettings} from './business';
import {defaultWebsite,mediaReferences,type Website} from './website-model';
export async function publicBusiness(){const b=await businessSettings();return {name:b.name,ownerName:b.ownerName,phone:b.phone,email:b.email,website:b.website}}
export async function publishedWebsite():Promise<Website>{const row=await rawDb().prepare("SELECT published_json FROM website_content WHERE id='owner'").first<any>(),contact=await publicBusiness();return row?{...JSON.parse(row.published_json),contact}:defaultWebsite(contact)}
export async function editorState(){const db=rawDb(),existing=await db.prepare("SELECT * FROM website_content WHERE id='owner'").first<any>();if(existing)return existing;
 const contact=await publicBusiness(),initial=defaultWebsite(contact),business=await businessSettings(),now=new Date().toISOString(),statements: ReturnType<ReturnType<typeof rawDb>["prepare"]>[]=[];
 // Adopt the existing public owner photo without moving, compressing or deleting it.
 if(business.ownerPhotoKey){const bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(business.ownerPhotoKey))),hex=Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join(''),id=hex.slice(0,8)+'-'+hex.slice(8,12)+'-'+hex.slice(12,16)+'-'+hex.slice(16,20)+'-'+hex.slice(20,32);initial.about.photo=id;statements.push(db.prepare("INSERT OR IGNORE INTO website_media (id,object_key,name,content_type,category,created_at) VALUES (?,?,'Current owner photograph','image/jpeg','owner',?)").bind(id,business.ownerPhotoKey,now))}
 const json=JSON.stringify(initial);statements.push(db.prepare("INSERT OR IGNORE INTO website_content (id,draft_json,published_json,base_contact_json,updated_at) VALUES ('owner',?,?,?,?)").bind(json,json,JSON.stringify(contact),now),db.prepare("INSERT OR IGNORE INTO website_versions (id,content_json,description,created_at) SELECT 'original',published_json,'Original website',updated_at FROM website_content WHERE id='owner'"));if(initial.about.photo)statements.push(db.prepare('INSERT OR IGNORE INTO website_public_media (media_id) VALUES (?)').bind(initial.about.photo));await db.batch(statements);return db.prepare("SELECT * FROM website_content WHERE id='owner'").first<any>()}
export async function checkMedia(content:Website){const db=rawDb();for(const id of mediaReferences(content)){if(!await db.prepare('SELECT id FROM website_media WHERE id=?').bind(id).first())throw Error('A selected business photo is missing. Choose another photo.')}}
