export type Words={en:string;es:string};
export type Service={id:string;name:Words;description:Words;photo:string;active:boolean;bookable:boolean;prices:{base:number;small:number;large:number;twoStory:number;bundle:number;bundleLarge:number;bundleTwoStory:number;minimum:number;rangeExtra:number}};
const words=(en:string,es=en):Words=>({en,es});
export const defaultServices:Service[]=[
 ['driveway','Driveway','Entrada','One wide photo','Una foto amplia',120,120,120,120,60,60,60,20],
 ['patio','Patio','Patio','Sized to your space','Según el tamaño de tu espacio',210,180,240,210,140,170,140,0],
 ['walkways','Walkways','Pasillos','Front, side, or rear paths','Pasillos al frente, lados o atrás',120,120,120,120,40,40,40,20],
 ['exterior','Exterior walls','Paredes exteriores','Professional soap rinse','Enjuague profesional con jabón',360,360,360,450,280,280,360,0],
 ['whole','Entire property','Propiedad completa','A complete front, sides, rear, and exterior wash','Limpieza del frente, lados, parte trasera y exterior',450,450,450,550,450,450,550,0],
 ['commercial','Commercial property','Propiedad comercial','Flexible access and scheduling','Acceso y horarios flexibles',525,525,525,525,400,400,400,0]
].map(([id,en,es,de,ds,base,small,large,twoStory,bundle,bundleLarge,bundleTwoStory,rangeExtra])=>({id:String(id),name:words(String(en),String(es)),description:words(String(de),String(ds)),photo:'',active:true,bookable:true,prices:{base:Number(base),small:Number(small),large:Number(large),twoStory:Number(twoStory),bundle:Number(bundle),bundleLarge:Number(bundleLarge),bundleTwoStory:Number(bundleTwoStory),minimum:0,rangeExtra:Number(rangeExtra)}}));
export const sectionNames={hero:'Welcome',services:'Services',about:'About you',portfolio:'Before & after',faq:'Questions',areas:'Service areas'};
export type Website={hero:{heading:Words;body:Words;eyebrow:Words;button:Words;photo:string};about:{heading:Words;body:Words;photo:string};sections:{id:keyof typeof sectionNames;visible:boolean}[];services:Service[];faqs:{id:string;question:Words;answer:Words}[];portfolio:{id:string;before:string;after:string;caption:Words}[];areas:Words;promotion:{enabled:boolean;message:Words;start:string;end:string;placement:'top'|'below'};contact:{name:string;ownerName:string;phone:string;email:string;website:string}};
export function defaultWebsite(contact:Website['contact']):Website{return {hero:{heading:words('A cleaner property\nstarts with a photo.','Una propiedad más limpia\nempieza con una foto.'),body:words('Get a personalized cleaning plan, transparent estimate, and appointment—all from your phone. No sales call required for jobs up to $500.','Recibe un plan personalizado, un precio claro y una cita—todo desde tu teléfono.'),eyebrow:words('Estimates without the back-and-forth','Estimados sin complicaciones'),button:words('Get my estimate','Obtener mi estimado'),photo:''},about:{heading:words('Know who’s coming to your property.','Conoce quién viene a tu propiedad.'),body:words('I’m Edgar. I personally review each cleaning plan and handle your service from estimate to final walkthrough.','Soy Edgar. Reviso personalmente cada plan de limpieza y me encargo de tu servicio desde el estimado hasta la revisión final.'),photo:''},sections:Object.keys(sectionNames).map(id=>({id:id as keyof typeof sectionNames,visible:id==='hero'})),services:structuredClone(defaultServices),faqs:[],portfolio:[],areas:words('Lawndale, Hawthorne, Gardena, Redondo Beach, Manhattan Beach, Torrance, El Segundo, Inglewood, Carson, San Pedro, Culver City, Compton, Long Beach, Los Angeles, Santa Monica'),promotion:{enabled:false,message:words(''),start:'',end:'',placement:'top'},contact}};
export function serviceRange(s:Service){const p=s.prices;const min=Math.max(p.minimum,s.id==='patio'?p.small:p.base),max=Math.max(min,s.id==='patio'?p.large:['whole','exterior'].includes(s.id)?p.twoStory:p.base+p.rangeExtra);return min===max?`$${min}`:`$${min}–$${max}`}
export function mediaReferences(w:Website){return [...new Set([w.hero.photo,w.about.photo,...w.services.map(s=>s.photo),...w.portfolio.flatMap(p=>[p.before,p.after])].filter(Boolean))]}
export function validateWebsite(value:any):Website{
 const text=(v:any,n=2000)=>{if(typeof v!=='string'||v.length>n)throw Error('Please shorten the text in this section.');return v.trim()};
 const w=(v:any):Words=>({en:text(v?.en),es:text(v?.es)}),photo=(v:any)=>{if(typeof v!=='string'||(v&&!/^[a-f0-9-]{36}$/.test(v)))throw Error('Choose a photo from your business library.');return v};
 const services=defaultServices.map(d=>{const v=value.services?.find((x:any)=>x.id===d.id);if(!v)throw Error('Keep all supported services; use the Active switch to hide one.');const prices={} as Service['prices'];for(const k of Object.keys(d.prices) as (keyof Service['prices'])[]){const n=Number(v.prices?.[k]);if(!Number.isFinite(n)||n<0||n>100000||Math.abs(Math.round(n*100)-n*100)>.00001)throw Error('Enter valid prices with at most two decimals.');prices[k]=n}if(!v.name?.en?.trim()||prices.base<=0||prices.small>prices.large)throw Error('Each service needs a name and valid prices.');return {id:d.id,name:w(v.name),description:w(v.description),photo:photo(v.photo),active:!!v.active,bookable:!!v.bookable,prices}});
 if(!services.some(s=>s.active&&s.bookable))throw Error('Keep at least one service available for booking.');
 if(!Array.isArray(value.sections)||value.sections.length!==6||new Set(value.sections.map((s:any)=>s.id)).size!==6||value.sections.some((s:any)=>!Object.hasOwn(sectionNames,s.id)))throw Error('Keep the six supported sections.');
 if(value.faqs?.length>20||value.portfolio?.length>12||!Array.isArray(value.faqs)||!Array.isArray(value.portfolio))throw Error('Use up to 20 questions and 12 before/after pairs.');
 const date=(v:any)=>{if(v===''||/^\d{4}-\d{2}-\d{2}$/.test(v)&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v)return v;throw Error('Choose valid promotion dates.')};
 const contact={name:text(value.contact?.name,120),ownerName:text(value.contact?.ownerName,120),phone:text(value.contact?.phone,30),email:text(value.contact?.email,200),website:text(value.contact?.website,250)};
 if(!contact.name||!contact.ownerName||!/^\+?[\d\s().-]{10,22}$/.test(contact.phone)||!/^\S+@\S+\.\S+$/.test(contact.email)||!/^https:\/\/[a-z0-9.-]+(?::\d+)?\/?$/i.test(contact.website))throw Error('Check the business name, contact details and HTTPS website address.');
 const promotion={enabled:!!value.promotion?.enabled,message:w(value.promotion?.message),start:date(value.promotion?.start),end:date(value.promotion?.end),placement:value.promotion?.placement==='below'?'below' as const:'top' as const};if(promotion.start&&promotion.end&&promotion.start>promotion.end)throw Error('The promotion end must be after its start.');if(promotion.enabled&&!promotion.message.en)throw Error('Add a message before activating your announcement.');
 if(!value.hero?.heading?.en?.trim()||!value.hero?.button?.en?.trim())throw Error('Add a homepage heading and estimate button label.');
 return {hero:{heading:w(value.hero?.heading),body:w(value.hero?.body),eyebrow:w(value.hero?.eyebrow),button:w(value.hero?.button),photo:photo(value.hero?.photo)},about:{heading:w(value.about?.heading),body:w(value.about?.body),photo:photo(value.about?.photo)},sections:value.sections.map((s:any)=>({id:s.id,visible:s.id==='hero'||!!s.visible})),services,faqs:value.faqs.map((f:any,i:number)=>({id:String(i),question:w(f.question),answer:w(f.answer)})),portfolio:value.portfolio.map((p:any,i:number)=>({id:String(i),before:photo(p.before),after:photo(p.after),caption:w(p.caption)})),areas:w(value.areas),promotion,contact};
}
