// Conservative, advisory pixel checks. No original file is rewritten.
export function pixelQuality(rgba,width,height,originalWidth=width,originalHeight=height){
 const n=width*height,g=new Float32Array(n);let sum=0,sq=0,dark=0,bright=0;
 for(let i=0;i<n;i++){const v=.2126*rgba[i*4]+.7152*rgba[i*4+1]+.0722*rgba[i*4+2];g[i]=v;sum+=v;sq+=v*v;if(v<25)dark++;if(v>248)bright++}
 const mean=sum/n,contrast=Math.sqrt(Math.max(0,sq/n-mean*mean));let lap=0,lapSq=0,count=0;
 for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const i=y*width+x,v=4*g[i]-g[i-1]-g[i+1]-g[i-width]-g[i+width];lap+=v;lapSq+=v*v;count++}
 const sharpness=count?lapSq/count-(lap/count)**2:0,issues=[];
 if(Math.min(originalWidth,originalHeight)<240||originalWidth*originalHeight<180000)issues.push('resolution');
 if(mean<30&&dark/n>.78)issues.push('dark');
 if(bright/n>.88&&contrast<32)issues.push('exposure');
 if(!issues.includes('dark')&&!issues.includes('exposure')&&sharpness<3&&contrast>12&&Math.min(originalWidth,originalHeight)>400)issues.push('blur');
 if(Math.max(originalWidth,originalHeight)/Math.min(originalWidth,originalHeight)>4.5)issues.push('framing');
 return {width:originalWidth,height:originalHeight,mean,contrast,sharpness,issues};
}
export const qualityMessages={resolution:['This photo is very small. Please upload the original camera photo so we can see details.','Esta foto es muy pequeña. Sube la foto original de la cámara para ver los detalles.'],dark:['This photo looks too dark. Retake it in daylight, with the area clearly visible.','La foto se ve muy oscura. Tómala de nuevo con luz de día.'],exposure:['Most detail looks washed out. Avoid pointing toward the sun and lower the camera exposure.','Casi no se ven detalles por el exceso de luz. Evita apuntar al sol y baja la exposición.'],blur:['This photo may be too blurry to assess. Clean the lens, hold still and tap the area to focus.','La foto puede estar demasiado borrosa. Limpia la lente, mantén la cámara firme y toca el área para enfocar.'],framing:['This photo is very narrow. Step back and include the full area, plus any close-ups.','Esta foto es muy estrecha. Retrocede e incluye toda el área, además de los acercamientos.'],unsupported:['We could not check this format. The original is still kept; make sure the area is clear.','No pudimos revisar este formato. Conservamos el original; asegúrate de que el área se vea claramente.']};
export async function decodePhoto(file,max=1000){const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,canvas.width,canvas.height);return {canvas,width:image.naturalWidth,height:image.naturalHeight}}finally{URL.revokeObjectURL(url)}}
export async function analyzePhoto(file){try{const {canvas,width,height}=await decodePhoto(file,512),pixels=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);return pixelQuality(pixels.data,canvas.width,canvas.height,width,height)}catch{return {issues:['unsupported']}}}
export async function photoHash(file){try{const {canvas}=await decodePhoto(file,1000),tiny=document.createElement('canvas');tiny.width=9;tiny.height=8;const c=tiny.getContext('2d');c.drawImage(canvas,0,0,9,8);const d=c.getImageData(0,0,9,8).data;let bits='';for(let y=0;y<8;y++)for(let x=0;x<8;x++){const a=(y*9+x)*4,b=a+4;bits+=(d[a]+d[a+1]+d[a+2])>(d[b]+d[b+1]+d[b+2])?'1':'0'}return Array.from({length:16},(_,i)=>parseInt(bits.slice(i*4,i*4+4),2).toString(16)).join('')}catch{return ''}}
