import {rawDb} from '../../../../db';
import {ownerAuthorized,forbidden} from '../../owner-auth';
import {clean,isoDate,failure} from '../../records-utils';
import {draftTrip,mileageRate,routeMiles,routingReady,mileageSettings} from '../../../../lib/job-costs';
const bad=(error:string,status=400)=>Response.json({error},{status});
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const db=rawDb(),[settings,vehicles,trips,supplies,movements,links,legacy]=await Promise.all([db.prepare("SELECT * FROM cost_settings WHERE id='owner'").first(),db.prepare('SELECT * FROM vehicles ORDER BY archived,nickname').all(),db.prepare('SELECT t.*,v.nickname AS vehicle FROM trip_records t LEFT JOIN vehicles v ON v.id=t.vehicle_id ORDER BY trip_date DESC,created_at DESC').all(),db.prepare("SELECT s.*,COALESCE((SELECT SUM(quantity) FROM supply_movements WHERE supply_id=s.id),0) AS stock,COALESCE((SELECT SUM(quantity*unit_cost)/NULLIF(SUM(quantity),0) FROM supply_movements WHERE supply_id=s.id AND quantity>0),0) AS unit_cost FROM supplies s ORDER BY archived,name").all(),db.prepare('SELECT m.*,s.name,s.unit FROM supply_movements m JOIN supplies s ON s.id=m.supply_id ORDER BY movement_date DESC,created_at DESC').all(),db.prepare('SELECT l.*,c.first_name,c.last_name,j.service,j.status AS job_status FROM trip_jobs l JOIN jobs j ON j.id=l.job_id JOIN customers c ON c.id=j.customer_id').all(),db.prepare('SELECT *,round(end_odometer-start_odometer,1) AS miles FROM mileage').all()]);return Response.json({settings:await mileageSettings(),vehicles:vehicles.results,trips:trips.results,supplies:supplies.results,movements:movements.results,links:links.results,legacy:legacy.results,routingReady:routingReady()},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const b=await r.json() as any,db=rawDb(),id=clean(b.id)||crypto.randomUUID();
 if(b.action==='sync_mileage'){const rows=await db.prepare("SELECT j.id FROM jobs j LEFT JOIN trip_jobs l ON l.job_id=j.id LEFT JOIN trip_records t ON t.id=l.trip_id WHERE j.status!='Cancelled' AND (l.job_id IS NULL OR (t.status='draft' AND j.status IN ('Completed','Paid','Invoice sent','Invoice ready')) OR (t.estimated_miles IS NULL AND t.actual_miles IS NULL)) ORDER BY j.created_at DESC LIMIT 40").all<any>();for(let i=0;i<rows.results.length;i+=4)await Promise.all(rows.results.slice(i,i+4).map(x=>draftTrip(x.id)));return Response.json({ok:true})}
 if(b.action==='edit_reference'){
 const t=await db.prepare('SELECT * FROM trip_records WHERE id=?').bind(id).first<any>();if(!t)return bad('Mileage not found.',404);
 const miles=Number(b.miles);if(!Number.isFinite(miles)||miles<0||miles>10000||!isoDate(b.date))return bad('Enter a valid trip date and miles.');
 const vehicle=clean(b.vehicleId)||t.vehicle_id;if(vehicle&&!await db.prepare('SELECT id FROM vehicles WHERE id=?').bind(vehicle).first())return bad('Choose a saved vehicle.');
 const route=String(b.route||'').split('\n').map(x=>clean(x)).filter(Boolean);if(route.length<2||route.length>25)return bad('Enter the route, one stop per line.');
 const after={actual_miles:miles,trip_date:b.date,vehicle_id:vehicle,route_json:JSON.stringify(route)};
 await db.batch([db.prepare('INSERT INTO trip_edits (id,trip_id,before_json,after_json,reason) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),id,JSON.stringify(t),JSON.stringify(after),clean(b.reason)||'Owner mileage correction'),db.prepare("UPDATE trip_records SET actual_miles=?,trip_date=?,vehicle_id=?,route_json=?,eligible_miles=NULL,rate=NULL,confirmed_at=NULL,status=CASE WHEN status='confirmed' THEN 'recorded' ELSE status END WHERE id=?").bind(miles,b.date,vehicle,JSON.stringify(route),id)]);return Response.json({ok:true})}
 if(b.action==='mileage_history'){const rows=await db.prepare('SELECT * FROM trip_edits WHERE trip_id=? ORDER BY created_at DESC').bind(id).all();return Response.json({history:rows.results})}
 if(b.action==='settings'){if(b.vehicleId&&!await db.prepare('SELECT id FROM vehicles WHERE id=? AND archived=0').bind(clean(b.vehicleId)).first())return bad('Choose an active vehicle.');await db.prepare("INSERT INTO cost_settings (id,base_address,default_vehicle) VALUES ('owner',?,?) ON CONFLICT(id) DO UPDATE SET base_address=excluded.base_address,default_vehicle=excluded.default_vehicle").bind(clean(b.baseAddress),clean(b.vehicleId)||null).run();return Response.json({ok:true})}
 if(b.action==='vehicle'){if(!clean(b.nickname))return bad('Name this vehicle.');const odo=b.startingOdometer===''||b.startingOdometer==null?null:Number(b.startingOdometer);if(odo!==null&&(!Number.isFinite(odo)||odo<0))return bad('Enter a valid starting odometer.');if(b.startDate&&!isoDate(b.startDate))return bad('Choose a valid date.');await db.prepare('INSERT INTO vehicles (id,nickname,details,plate,vin,starting_odometer,start_date) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET nickname=excluded.nickname,details=excluded.details,plate=excluded.plate,vin=excluded.vin,starting_odometer=excluded.starting_odometer,start_date=excluded.start_date').bind(id,clean(b.nickname),clean(b.details),clean(b.plate,20),clean(b.vin,17),odo,b.startDate||null).run();return Response.json({ok:true})}
 if(b.action==='archive_vehicle'||b.action==='delete_vehicle'){const used=await db.prepare('SELECT id FROM trip_records WHERE vehicle_id=? LIMIT 1').bind(id).first();if(b.action==='delete_vehicle'&&used)return bad('This vehicle has trip history. Archive it to preserve your records.');await db.batch([db.prepare("UPDATE cost_settings SET default_vehicle=NULL WHERE default_vehicle=?").bind(id),db.prepare(b.action==='delete_vehicle'?'DELETE FROM vehicles WHERE id=?':'UPDATE vehicles SET archived=? WHERE id=?').bind(...(b.action==='delete_vehicle'?[id]:[b.restore?0:1,id]))]);return Response.json({ok:true})}
 if(b.action==='draft'){const j=await db.prepare("SELECT id FROM jobs WHERE id=? AND status!='Cancelled'").bind(clean(b.jobId)).first();if(!j)return bad('Choose an active job.');await draftTrip(clean(b.jobId));return Response.json({ok:true})}
 if(['save_trip','calculate','confirm_trip','reopen_trip','delete_trip'].includes(b.action)){
 const t=await db.prepare('SELECT * FROM trip_records WHERE id=?').bind(id).first<any>();if(!t)return bad('Trip not found.',404);
 if(b.action==='reopen_trip'){await db.prepare("UPDATE trip_records SET status='draft',confirmed_at=NULL,rate=NULL WHERE id=?").bind(id).run();return Response.json({ok:true})}
 if(t.status==='confirmed')return bad('Reopen this trip before making corrections.');
 if(b.action==='delete_trip'){await db.batch([db.prepare('DELETE FROM trip_jobs WHERE trip_id=?').bind(id),db.prepare('DELETE FROM trip_records WHERE id=?').bind(id)]);return Response.json({ok:true})}
 const route=String(b.route||'').split('\n').map(x=>clean(x)).filter(Boolean);if(route.length<2||route.length>25||!isoDate(b.tripDate)||!clean(b.purpose))return bad('Enter a date, purpose, and at least a start and end address.');
 if(!await db.prepare('SELECT id FROM vehicles WHERE id=? AND archived=0').bind(clean(b.vehicleId)).first())return bad('Choose an active vehicle.');
 let estimated:number|null=null;if(b.action==='calculate'){try{estimated=await routeMiles(route)}catch(e){return bad((e as Error).message)}}
 const actual=b.actualMiles===''||b.actualMiles==null?null:Number(b.actualMiles),eligible=b.eligibleMiles===''||b.eligibleMiles==null?null:Number(b.eligibleMiles),method=['review','standard','actual'].includes(b.method)?b.method:'review';
 if(actual!==null&&(!Number.isFinite(actual)||actual<=0||actual>10000))return bad('Enter actual miles greater than zero.');if(eligible!==null&&(!Number.isFinite(eligible)||eligible<0||actual===null||eligible>actual))return bad('Eligible business miles must be between zero and the actual miles.');if(b.action==='confirm_trip'&&(actual===null||!b.attested))return bad('Confirm the miles reflect the route you actually drove.');
 await db.prepare('UPDATE trip_records SET trip_date=?,vehicle_id=?,route_json=?,purpose=?,estimated_miles=?,actual_miles=?,eligible_miles=?,method=?,status=?,rate=?,confirmed_at=? WHERE id=?').bind(b.tripDate,b.vehicleId,JSON.stringify(route),clean(b.purpose),estimated??(JSON.stringify(route)===t.route_json?t.estimated_miles:null),actual,eligible,method,b.action==='confirm_trip'?'confirmed':'draft',b.action==='confirm_trip'&&method==='standard'?mileageRate(b.tripDate):null,b.action==='confirm_trip'?new Date().toISOString():null,id).run();return Response.json({ok:true})}
 if(b.action==='merge_trips'){const ids=[...new Set((b.ids||[]).map((x:any)=>clean(x)))];if(ids.length<2||ids.length>20)return bad('Select at least two unconfirmed trips.');const rows=await db.prepare(`SELECT * FROM trip_records WHERE id IN (${ids.map(()=>'?').join(',')})`).bind(...ids).all<any>();if(rows.results.length!==ids.length||rows.results.some(t=>t.status!=='draft'||t.trip_date!==rows.results[0].trip_date))return bad('Only drafts on the same date can be combined.');const first=rows.results[0],routes=rows.results.map(t=>JSON.parse(t.route_json)),combined=[routes[0][0],...routes.flatMap(x=>x.slice(1,-1)),routes[0].at(-1)];await db.batch([db.prepare('UPDATE trip_records SET route_json=?,estimated_miles=NULL,actual_miles=NULL,eligible_miles=NULL WHERE id=?').bind(JSON.stringify(combined),first.id),...rows.results.filter(t=>t.id!==first.id).flatMap(t=>[db.prepare('UPDATE trip_jobs SET trip_id=? WHERE trip_id=?').bind(first.id,t.id),db.prepare('DELETE FROM trip_records WHERE id=?').bind(t.id)])]);return Response.json({ok:true})}
 if(b.action==='supply'){if(!clean(b.name)||!['gallon','bottle','liter','each'].includes(b.unit)||!Number.isFinite(Number(b.lowAt))||Number(b.lowAt)<0)return bad('Enter a supply name, unit, and low-stock level.');await db.prepare('INSERT INTO supplies (id,name,unit,low_at) VALUES (?,?,?,?)').bind(id,clean(b.name),b.unit,Number(b.lowAt)).run();return Response.json({ok:true})}
 if(b.action==='archive_supply'){await db.prepare('UPDATE supplies SET archived=? WHERE id=?').bind(b.restore?0:1,id).run();return Response.json({ok:true})}
 if(b.action==='stock'||b.action==='usage'){
 const s=await db.prepare('SELECT * FROM supplies WHERE id=? AND archived=0').bind(clean(b.supplyId)).first<any>(),q=Number(b.quantity);if(!s||!Number.isFinite(q)||q<=0||q>100000||!isoDate(b.date))return bad('Choose a supply, positive quantity, and date.');
 if(b.action==='usage'){if(!await db.prepare('SELECT id FROM jobs WHERE id=?').bind(clean(b.jobId)).first())return bad('Choose a job.');const result=await db.prepare("INSERT INTO supply_movements (id,supply_id,quantity,unit_cost,kind,job_id,movement_date,note) SELECT ?,?,-?,COALESCE((SELECT SUM(quantity*unit_cost)/NULLIF(SUM(quantity),0) FROM supply_movements WHERE supply_id=? AND quantity>0),0),'usage',?,?,? WHERE COALESCE((SELECT SUM(quantity) FROM supply_movements WHERE supply_id=?),0)>=?").bind(id,s.id,q,s.id,b.jobId,b.date,clean(b.note),s.id,q).run();if(!result.meta.changes)return bad('Not enough stock. Record a purchase or opening stock first.');return Response.json({ok:true})}
 let cost=0,expenseId=null;if(b.expenseId){const expense=await db.prepare('SELECT * FROM expenses WHERE id=?').bind(clean(b.expenseId)).first<any>();if(!expense)return bad('Choose a saved purchase expense.');const previous=await db.prepare('SELECT id FROM supply_movements WHERE expense_id=?').bind(expense.id).first();if(previous)return bad('That purchase is already linked to stock.');cost=Number(expense.amount)/q;expenseId=expense.id}else{cost=Number(b.unitCost||0);if(!Number.isFinite(cost)||cost<0)return bad('Enter a valid unit cost.');if(!b.opening)return bad('Link a saved expense or choose opening stock.');}
 await db.prepare("INSERT INTO supply_movements (id,supply_id,quantity,unit_cost,kind,expense_id,movement_date,note) VALUES (?,?,?,?,'stock',?,?,?)").bind(id,s.id,q,cost,expenseId,b.date,clean(b.note)||(!expenseId?'Opening stock — not an expense':'Purchase')).run();return Response.json({ok:true})}
 if(b.action==='undo_usage'){await db.prepare("DELETE FROM supply_movements WHERE id=? AND kind='usage'").bind(id).run();return Response.json({ok:true})}
 return bad('Choose an action.');}catch(e){return failure(e)}}
