import {rawDb} from '../../../../db';import {ownerAuthorized,forbidden} from '../../owner-auth';import {businessSettings} from '../../../../lib/business';import {marketingCategories,captionSuggestion} from '../../../../lib/marketing';
const json=(v:any,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private, no-store'}});
async function mediaRows(){return (await rawDb().prepare(`SELECT 'job' AS kind,m.id,m.file_name AS name,m.content_type,m.job_id,j.service,j.status AS job_status,m.created_at,CASE WHEN a.id IS NULL THEN 0 ELSE 1 END AS approved FROM media m JOIN jobs j ON j.id=m.job_id LEFT JOIN marketing_approvals a ON a.id='job:'||m.id UNION ALL SELECT 'website',w.id,w.name,w.content_type,NULL,w.category,'Business media',w.created_at,CASE WHEN a.id IS NULL THEN 0 ELSE 1 END FROM website_media w LEFT JOIN marketing_approvals a ON a.id='website:'||w.id WHERE w.archived=0 ORDER BY created_at DESC`).all<any>()).results.map(m=>({...m,key:m.kind+':'+m.id,url:m.kind==='job'?'/api/owner/media/'+m.id:'/api/owner/website/media/'+m.id}));}
async function approved(ids:string[]){const rows=await mediaRows();return ids.length>0&&ids.every(id=>rows.some(m=>m.key===id&&m.approved));}
export async function GET(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const db=rawDb(),b=await businessSettings(),posts=(await db.prepare('SELECT * FROM marketing_posts ORDER BY updated_at DESC').all<any>()).results.map(p=>({...p,content:JSON.parse(p.content_json)}));const stats=(await db.prepare("SELECT campaign,count(*) AS estimate_starts,sum(CASE WHEN booked_at IS NOT NULL THEN 1 ELSE 0 END) AS bookings FROM estimate_funnels WHERE campaign LIKE 'pu-post-%' GROUP BY campaign").all()).results;const revenue=(await db.prepare("SELECT campaign,sum(price) AS booked_revenue FROM jobs WHERE campaign LIKE 'pu-post-%' AND status IN ('Confirmed','In progress','Completed','Invoice sent','Paid') GROUP BY campaign").all()).results;return json({media:await mediaRows(),posts,stats,revenue,business:{name:b.name,website:b.website},categories:marketingCategories})}catch{return json({error:'Could not load Marketing Center. Try again.'},500)}}
export async function POST(r:Request){if(!(await ownerAuthorized(r)))return forbidden();try{const b=await r.json() as any,db=rawDb(),now=new Date().toISOString();
 if(b.action==='media'){const rows=await mediaRows(),m=rows.find(x=>x.key===b.key);if(!m)return json({error:'Media not found.'},404);if(b.approved){if(b.confirm!==true)return json({error:'Confirm you have permission to use this media publicly.'},400);await db.prepare('INSERT OR REPLACE INTO marketing_approvals (id,kind,media_id,approved_at) VALUES (?,?,?,?)').bind(m.key,m.kind,m.id,now).run()}else await db.prepare('DELETE FROM marketing_approvals WHERE id=?').bind(m.key).run();return json({ok:true})}
 if(b.action==='suggest'){const business=await businessSettings();return json({caption:captionSuggestion(String(b.category),String(b.service||'').slice(0,100),String(b.location||'').slice(0,80),business.name,business.website)})}
 const existing=b.id?await db.prepare('SELECT * FROM marketing_posts WHERE id=?').bind(String(b.id)).first<any>():null;
 if(b.action==='save'){if(b.id&&!existing)return json({error:'Post not found.'},404);if(existing&&b.token!==existing.token)return json({error:'This post changed. Reload before saving.'},409);const c=b.content||{},media=Array.isArray(c.media)?[...new Set(c.media)].slice(0,4) as string[]:[];if(!await approved(media))return json({error:'Select only media currently Approved for Marketing.'},409);if(!marketingCategories.includes(c.category)||!['Post','Story','Reel'].includes(c.format))return json({error:'Choose a category and format.'},400);const content={category:c.category,format:c.format,media,caption:String(c.caption||'').slice(0,2200),service:String(c.service||'').slice(0,100),location:String(c.location||'').slice(0,80),headline:String(c.headline||'').slice(0,70),campaign:existing?JSON.parse(existing.content_json).campaign:'pu-post-'+crypto.randomUUID(),attribution:{websiteVisits:null,platformReach:null,engagement:null}};const id=existing?.id||crypto.randomUUID(),token=crypto.randomUUID();if(existing){const result=await db.prepare("UPDATE marketing_posts SET content_json=?,state='Draft',token=?,updated_at=? WHERE id=? AND token=?").bind(JSON.stringify(content),token,now,id,b.token).run();if(!result.meta.changes)return json({error:'Post changed. Reload before saving.'},409)}else await db.prepare("INSERT INTO marketing_posts (id,content_json,state,token,created_at,updated_at) VALUES (?,?,'Draft',?,?,?)").bind(id,JSON.stringify(content),token,now,now).run();return json({ok:true,id})}
 if(!existing)return json({error:'Post not found.'},404);if(b.token!==existing.token)return json({error:'Post changed. Reload it first.'},409);const c=JSON.parse(existing.content_json);if(!await approved(c.media))return json({error:'Media approval was removed or a file is unavailable. Approve eligible media before continuing.'},409);
 const next=b.action==='review'&&existing.state==='Draft'?'Review':b.action==='approve'&&existing.state==='Review'&&b.confirm===true?'Approved':b.action==='export'&&['Approved','Exported'].includes(existing.state)?'Exported':null;if(!next)return json({error:'Follow Draft → Review → Approve → Export.'},409);if(!c.caption.trim()||(/Add (an exact|your approved)/.test(c.caption)))return json({error:'Finish and check the caption before review.'},400);
 // Approval is checked again in the same write, including revocation on another device.
 const placeholders=c.media.map(()=>'?').join(','),result=await db.prepare(`UPDATE marketing_posts SET state=?,token=?,updated_at=? WHERE id=? AND token=? AND (SELECT count(*) FROM marketing_approvals WHERE id IN (${placeholders}))=?`).bind(next,crypto.randomUUID(),now,existing.id,b.token,...c.media,c.media.length).run();if(!result.meta.changes)return json({error:'Post or media approval changed. Reload before continuing.'},409);
 if(b.action==='export'){const business=await businessSettings(),url=new URL(business.website);url.searchParams.set('utm_source','Instagram');url.searchParams.set('utm_medium','social');url.searchParams.set('utm_campaign',c.campaign);const media=(await mediaRows()).filter(m=>c.media.includes(m.key));return json({ok:true,export:{...c,id:existing.id,caption:(c.caption.includes(business.website)?c.caption.replaceAll(business.website,url.toString()):c.caption+'\n\n'+url.toString()),trackingUrl:url.toString(),business:business.name,media:media.map(m=>({key:m.key,url:m.url,type:m.content_type})),instructions:'Download the caption and image/video. Review privacy and upload manually to Meta Business Suite. Exported does not mean posted.'}})}return json({ok:true});
 }catch{return json({error:'Could not save this change. Try again.'},400)}}
