"use client";
import {useState,useEffect} from 'react';
const btn='rounded-full border border-[#d7ded8] px-4 py-2 text-sm font-medium disabled:opacity-40';
export default function ContactActions({job,customer,onUpdate}:{job:any;customer:any;onUpdate:()=>Promise<void>}){
 const[form,setForm]=useState(''),[eta,setEta]=useState(''),[message,setMessage]=useState(''),[channel,setChannel]=useState('manual'),[ready,setReady]=useState<any>({}),[busy,setBusy]=useState(false),[result,setResult]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/owner/communicate').then(r=>r.json()).then(setReady).catch(()=>{})},[]);
 async function send(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/owner/communicate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:form,jobId:job.id,eta,message,channel})}),d=await r.json();if(!r.ok)throw Error(d.error);setResult(d);await onUpdate()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const sms=(text:string)=>`sms:${customer.phone}${/iPad|iPhone|iPod/.test(typeof navigator!=='undefined'?navigator.userAgent:'')?'&':'?'}body=${encodeURIComponent(text)}`;
 return <div className="space-y-3"><a className="block font-semibold underline" href={sms('')}>{customer.phone}</a>{<div className="flex flex-wrap gap-2"><a className={btn} href={`tel:${customer.phone}`}>Call</a><a className={btn} href={sms('')}>Text</a><button className={btn} onClick={()=>{setForm('message');setMessage('');setResult(null)}}>Compose message</button></div>}<p className="break-all text-sm">{customer.email}</p>{!['Cancelled','Completed','Paid'].includes(job.status)&&<button className={btn+' bg-[#173b32] text-white'} onClick={()=>{setForm('eta');setEta('');setMessage('');setResult(null)}}>On my way</button>}{form&&<form className="space-y-3 rounded-xl border bg-white p-3" onSubmit={send}>{form==='eta'?<label className="block text-sm">Your ETA<input required maxLength={80} value={eta} onChange={e=>setEta(e.target.value)} placeholder="12:20 PM, or about 20 minutes" className="mt-1 w-full rounded-xl border p-3 text-base"/><span className="mt-2 block text-zinc-500">You set the arrival estimate. It also appears on the customer’s appointment page.</span></label>:<label className="block text-sm">Message<textarea required rows={4} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} className="mt-1 w-full rounded-xl border p-3 text-base"/></label>}<label className="block text-sm">Send with<select value={channel} onChange={e=>setChannel(e.target.value)} className="mt-1 w-full rounded-xl border p-3 text-base"><option value="manual">My phone’s text app</option><option value="sms" disabled={!ready.sms}>Business text{ready.sms?'':' — needs connection'}</option><option value="email" disabled={!ready.email}>Email{ready.email?'':' — needs connection'}</option></select></label>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex flex-wrap gap-2"><button disabled={busy} className={btn+' bg-[#173b32] text-white'}>{busy?'Saving…':channel==='manual'?(form==='eta'?'Save ETA & prepare text':'Prepare text'):'Send update'}</button><button type="button" className={btn} onClick={()=>{setForm('');setResult(null)}}>Close</button></div>{result&&<div role="status" className="space-y-2 rounded-xl bg-[#edf4ee] p-3 text-sm"><p>{result.portalUpdated?'Arrival updated on the customer page. ':''}{result.status==='draft'?'Text is ready for you to send.':result.status==='accepted by provider'?'Accepted by the sending service; delivery is not yet confirmed.':result.notice||result.status}</p><p className="whitespace-pre-wrap">{result.message}</p>{channel==='manual'&&<a href={sms(result.message)} className={btn+' inline-block bg-white'}>Open text app to send</a>}<p className="text-xs text-zinc-500">Texts sent from your personal phone stay in your phone’s conversation.</p></div>}</form>}</div>
}
