'use client';
import {useState} from 'react';import PdfActions from '../PdfActions';import SendDocument from './SendDocument';
const button='min-h-11 rounded-full border px-4 py-3 disabled:opacity-40',field='w-full min-w-0 rounded-xl border p-3';
export default function InvoiceEditor({job,info,run}:{job:any;info:any;run:(body:any,message?:string)=>Promise<boolean>}){
 const [editing,setEditing]=useState(false),[saved,setSaved]=useState(false),[items,setItems]=useState<any[]>([]),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false);
 if(!info)return <p>Loading invoice…</p>;const exists=job.invoiceJson!=='[]',state=job.paidAt?'Paid':info.state;
 async function act(body:any,message:string){setBusy(true);try{return await run({...body,token:info.token||undefined},message)}finally{setBusy(false)}}
 return <section className="space-y-4"><div><h3 className="text-xl font-semibold">Invoice · {state==='None'?'No invoice':state}</h3><p className="break-all text-sm text-zinc-500">{job.id} · Revision {info.revision}</p></div>{saved&&<p role="status">Saved ✓</p>}
 {exists&&!editing&&<><div className="space-y-2">{JSON.parse(job.invoiceJson).map((x:any,i:number)=><div className="flex justify-between gap-3" key={i}><span>{x.name}</span><b>${Number(x.amount).toFixed(2)}</b></div>)}</div>{state!=='Void'&&<PdfActions url={`/api/owner/documents?id=${job.id}&type=invoice`} name="invoice"/>}{['Draft','Sent','Paid'].includes(state)&&<SendDocument jobId={job.id} document="invoice" onPrepared={async()=>{await run({action:'refresh'},'Invoice link prepared. This version is protected.')}}/>}</>}
 {!editing&&!['Paid','Sent','Void'].includes(state)&&<button className={button} onClick={()=>{setItems(JSON.parse(exists?job.invoiceJson:job.estimateJson));setEditing(true);setSaved(false)}}>{exists?'Edit Invoice':'Create Invoice'}</button>}
 {editing&&<><div className="space-y-3">{items.map((x,i)=><div key={i} className="grid grid-cols-[minmax(0,1fr)_90px_44px] gap-2"><input className={field} aria-label={`Invoice line ${i+1}`} value={x.name} onChange={e=>setItems(items.map((y,k)=>k===i?{...y,name:e.target.value}:y))}/><input className={field} aria-label={`Amount ${i+1}`} type="number" step=".01" value={x.amount} onChange={e=>setItems(items.map((y,k)=>k===i?{...y,amount:e.target.value}:y))}/><button className={button} aria-label="Remove line" onClick={()=>setItems(items.filter((_,k)=>k!==i))}>×</button></div>)}</div><button className={button} onClick={()=>setItems([...items,{name:'',amount:0}])}>+ Line item</button><p className="font-semibold">Total: ${items.reduce((n,x)=>n+Number(x.amount||0),0).toFixed(2)}</p><div className="flex flex-wrap gap-2"><button className={button+' bg-[#173b32] text-white'} disabled={busy||!items.length} onClick={async()=>{if(await act({action:'document',document:'invoice',items},'Invoice saved.')){setSaved(true);setEditing(false)}}}>{busy?'Saving…':exists?'Save Changes':'Save Invoice'}</button><button className={button} disabled={busy} onClick={()=>setEditing(false)}>Discard edits</button></div></>}
 {state==='Sent'&&<><p className="text-sm">This issued version is protected. A correction starts a new draft and keeps the version your customer received.</p><button className={button} disabled={busy} onClick={()=>act({action:'revise_invoice'},'Correction draft created. Previous version preserved.')}>Create correction</button><button className={button} onClick={()=>setConfirm('VOID INVOICE')}>Void invoice</button></>}
 {state==='Draft'&&exists&&!info.versions.length&&!editing&&<button className={button+' text-red-700'} onClick={()=>setConfirm('DELETE DRAFT')}>Delete draft invoice</button>}
 {confirm&&<div role="alert" className="space-y-3 rounded-xl border border-red-300 p-4"><b>{confirm==='DELETE DRAFT'?'Permanently delete this unsent draft invoice?':'Void this unpaid invoice?'}</b><p className="text-sm">{confirm==='DELETE DRAFT'?'Invoice line items will be permanently removed. The customer and job remain. The job returns to its saved estimate amount.':'The issued version stays in history. Do not collect payment on a void invoice.'}</p><div className="flex flex-wrap gap-2"><button disabled={busy} className={button+' bg-red-700 text-white'} onClick={async()=>{if(await act({action:confirm==='DELETE DRAFT'?'delete_invoice':'void_invoice',confirm},confirm==='DELETE DRAFT'?'Draft invoice deleted. Customer and job preserved.':'Invoice voided.')){setConfirm('');setSaved(false)}}}>Confirm {confirm==='DELETE DRAFT'?'permanent deletion':'void'}</button><button className={button} onClick={()=>setConfirm('')}>Keep invoice</button></div></div>}
 {!!info.versions.length&&<details><summary className="min-h-11 cursor-pointer py-3">Issued versions</summary>{info.versions.map((v:any)=><div key={v.id} className="space-y-2 border-t py-3"><p>Revision {v.revision} · {new Date(v.created_at).toLocaleString()}</p><PdfActions url={`/api/owner/documents?id=${job.id}&type=invoice&revision=${v.revision}`} name={`invoice revision ${v.revision}`}/></div>)}</details>}
 </section>
}
